### ISSUE TITLE
[错误报告]QB老是无法连接 

### ISSUE THREAD

**Issue by aaaol** [EstrellaXD/Auto_Bangumi#102]
### 当前程序版本

2.5.24

### 问题类型

程序运行问题

### 问题描述

之前连上了  后面不知道为什么就连不上了
荒野的用了host用了 官方的Qb用了 我尝试过很多种办法

### 发生问题时系统日志

```shell
[2022-08-21 02:40:14,114] INFO:                     _        ____                                    _ 
[2022-08-21 02:40:14,115] INFO:          /\        | |      |  _ \                                  (_)
[2022-08-21 02:40:14,115] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _ 
[2022-08-21 02:40:14,115] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2022-08-21 02:40:14,115] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2022-08-21 02:40:14,115] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2022-08-21 02:40:14,115] INFO:                                                 __/ |                  
[2022-08-21 02:40:14,115] INFO:                                                |___/                   
[2022-08-21 02:40:14,115] INFO:     Version 2.5.24  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2022-08-21 02:40:14,115] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2022-08-21 02:40:14,115] INFO:     Starting AutoBangumi...
[2022-08-21 02:40:14,744] INFO:     No feed exists, start adding feed.
[2022-08-21 02:40:14,746] ERROR     该 RSS 项的路径已存在：Mikan_RSS。
Traceback (most recent call last):
  File "/src/downloader/qb_downloader.py", line 71, in rss_add_feed
    self._client.rss_add_feed(url, item_path)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/decorators.py", line 93, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/rss.py", line 176, in rss_add_feed
    self._post(_name=APINames.RSS, _method="addFeed", data=data, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 327, in _post
    return self._request_manager(
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 378, in _request_manager
    return self._request(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 439, in _request
    self._handle_error_responses(data, params, response)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 640, in _handle_error_responses
    raise Conflict409Error(response.text)
qbittorrentapi.exceptions.Conflict409Error: 该 RSS 项的路径已存在：Mikan_RSS。
```

**Comment by EstrellaXD** [comment]
删除qb中的rss订阅链接在进行尝试

**Comment by aaaol** [comment]
荒野无灯的qb没法用 原来没rss 功能
重新尝试后确实可以正常使用了
后续看看有没有有问题
