### ISSUE TITLE
[错误报告]qbittorrentapi.exceptions.Conflict409Error: 该 RSS 项的路径已存在：Mikan_RSS

### ISSUE THREAD

**Issue by InsaneDream233** [EstrellaXD/Auto_Bangumi#103]
### 当前程序版本

latest

### 问题类型

程序运行问题

### 问题描述

虽然是中文但我确实没看懂（

### 发生问题时系统日志

```shell
[2022-08-23 15:31:49,385] INFO:                     _        ____                                    _ 
[2022-08-23 15:31:49,385] INFO:          /\        | |      |  _ \                                  (_)
[2022-08-23 15:31:49,385] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _ 
[2022-08-23 15:31:49,386] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2022-08-23 15:31:49,386] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2022-08-23 15:31:49,386] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2022-08-23 15:31:49,386] INFO:                                                 __/ |                  
[2022-08-23 15:31:49,386] INFO:                                                |___/                   
[2022-08-23 15:31:49,386] INFO:     Version 2.5.25  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2022-08-23 15:31:49,386] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2022-08-23 15:31:49,386] INFO:     Starting AutoBangumi...
[2022-08-23 15:31:50,387] INFO:     No feed exists, start adding feed.
[2022-08-23 15:31:50,408] INFO:     Started server process [1]
[2022-08-23 15:31:50,408] INFO:     Waiting for application startup.
[2022-08-23 15:31:50,408] INFO:     Application startup complete.
[2022-08-23 15:31:50,409] INFO:     Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
[2022-08-23 15:31:50,440] ERROR     该 RSS 项的路径已存在：Mikan_RSS。
Traceback (most recent call last):
  File "/src/downloader/qb_downloader.py", line 71, in rss_add_feed
    self._client.rss_add_feed(url, item_path)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/decorators.py", line 92, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/rss.py", line 174, in rss_add_feed
    self._post(_name=APINames.RSS, _method="addFeed", data=data, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 350, in _post
    return self._request_manager(
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 401, in _request_manager
    return self._request(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 463, in _request
    self._handle_error_responses(data, params, response)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 669, in _handle_error_responses
    raise Conflict409Error(response.text)
qbittorrentapi.exceptions.Conflict409Error: 该 RSS 项的路径已存在：Mikan_RSS。
Traceback (most recent call last):
  File "/src/downloader/qb_downloader.py", line 71, in rss_add_feed
    self._client.rss_add_feed(url, item_path)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/decorators.py", line 92, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/rss.py", line 174, in rss_add_feed
    self._post(_name=APINames.RSS, _method="addFeed", data=data, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 350, in _post
    return self._request_manager(
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 401, in _request_manager
    return self._request(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 463, in _request
    self._handle_error_responses(data, params, response)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 669, in _handle_error_responses
    raise Conflict409Error(response.text)
qbittorrentapi.exceptions.Conflict409Error: 该 RSS 项的路径已存在：Mikan_RSS。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/app.py", line 111, in <module>
    run()
  File "/src/app.py", line 104, in run
    download_client.rss_feed()
  File "/src/core/download_client.py", line 62, in rss_feed
    self.client.rss_add_feed(url=settings.rss_link, item_path="Mikan_RSS")
  File "/src/downloader/qb_downloader.py", line 74, in rss_add_feed
    raise ConflictError()
downloader.exceptions.ConflictError
[root@rachel ~]# ^C
[root@rachel ~]# docker compose down
no configuration file provided: not found
[root@rachel ~]# cd AutoBangumi
[root@rachel AutoBangumi]# docker compose down
[+] Running 3/3
 ⠿ Container AutoBangumi        Removed                                                                                    0.3s
 ⠿ Container qBittorrent        Removed                                                                                    3.6s
 ⠿ Network autobangumi_default  Removed                                                                                    0.2s
[root@rachel AutoBangumi]# vim docker-compose.yml
[root@rachel AutoBangumi]# vim docker-compose.yml
[root@rachel AutoBangumi]# docker compose up -d
[+] Running 3/3
 ⠿ Network autobangumi_default  Created                                                                                    0.2s
 ⠿ Container qBittorrent        Started                                                                                    0.5s
 ⠿ Container AutoBangumi        Started                                                                                    0.8s
[root@rachel AutoBangumi]# docker logs AutoBangumi
获取webui最新版本号
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3657  100  3657    0     0   2281      0  0:00:01  0:00:01 --:--:--  2281
准备下载最新版本webui
Connecting to cdn.jsdelivr.net (146.75.113.229:443)
Connecting to raw.githubusercontent.com (185.199.111.133:443)
saving to 'dist.zip'
dist.zip              73% |***********************         |  143k  0:00:00 ETA
dist.zip             100% |********************************|  193k  0:00:00 ETA
'dist.zip' saved
Archive:  ./dist.zip
   creating: dist/
  inflating: dist/favicon.ico
   creating: dist/assets/
  inflating: dist/assets/el-button.170410e4.css
  inflating: dist/assets/index.a6639e6c.css
  inflating: dist/assets/index.aaa8ef6d.js
  inflating: dist/assets/YLayout.909c574a.css
  inflating: dist/assets/el-popper.f394526f.css
  inflating: dist/assets/index.1a7b13ed.css
  inflating: dist/assets/index.f7b3d004.js
  inflating: dist/assets/el-popper.7a7fe915.js
  inflating: dist/assets/YLayout.a7994478.js
  inflating: dist/assets/debug.f9425d76.js
  inflating: dist/assets/index.8ccc3d92.js
  inflating: dist/assets/index.562cf2fb.js
  inflating: dist/assets/index.a44b6412.css
  inflating: dist/assets/index.b0410c17.js
  inflating: dist/assets/index.7f9a9009.js
  inflating: dist/assets/logo.b7d483a4.png
  inflating: dist/assets/index.70730466.css
  inflating: dist/assets/el-button.e30122e8.js
  inflating: dist/index.html
  inflating: dist/robots.txt
webui下载完成
[2022-08-23 16:10:28,672] INFO:                     _        ____                                    _ 
[2022-08-23 16:10:28,672] INFO:          /\        | |      |  _ \                                  (_)
[2022-08-23 16:10:28,672] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _ 
[2022-08-23 16:10:28,672] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2022-08-23 16:10:28,672] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2022-08-23 16:10:28,672] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2022-08-23 16:10:28,672] INFO:                                                 __/ |                  
[2022-08-23 16:10:28,673] INFO:                                                |___/                   
[2022-08-23 16:10:28,673] INFO:     Version 2.5.25  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2022-08-23 16:10:28,673] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2022-08-23 16:10:28,673] INFO:     Starting AutoBangumi...
[2022-08-23 16:10:29,678] INFO:     No feed exists, start adding feed.
[2022-08-23 16:10:29,692] INFO:     Started server process [1]
[2022-08-23 16:10:29,692] INFO:     Waiting for application startup.
[2022-08-23 16:10:29,692] INFO:     Application startup complete.
[2022-08-23 16:10:29,693] INFO:     Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
[2022-08-23 16:10:29,729] ERROR     该 RSS 项的路径已存在：Mikan_RSS。
Traceback (most recent call last):
  File "/src/downloader/qb_downloader.py", line 71, in rss_add_feed
    self._client.rss_add_feed(url, item_path)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/decorators.py", line 92, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/rss.py", line 174, in rss_add_feed
    self._post(_name=APINames.RSS, _method="addFeed", data=data, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 350, in _post
    return self._request_manager(
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 401, in _request_manager
    return self._request(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 463, in _request
    self._handle_error_responses(data, params, response)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 669, in _handle_error_responses
    raise Conflict409Error(response.text)
qbittorrentapi.exceptions.Conflict409Error: 该 RSS 项的路径已存在：Mikan_RSS。
Traceback (most recent call last):
  File "/src/downloader/qb_downloader.py", line 71, in rss_add_feed
    self._client.rss_add_feed(url, item_path)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/decorators.py", line 92, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/rss.py", line 174, in rss_add_feed
    self._post(_name=APINames.RSS, _method="addFeed", data=data, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 350, in _post
    return self._request_manager(
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 401, in _request_manager
    return self._request(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 463, in _request
    self._handle_error_responses(data, params, response)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 669, in _handle_error_responses
    raise Conflict409Error(response.text)
qbittorrentapi.exceptions.Conflict409Error: 该 RSS 项的路径已存在：Mikan_RSS。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/app.py", line 111, in <module>
    run()
  File "/src/app.py", line 104, in run
    download_client.rss_feed()
  File "/src/core/download_client.py", line 62, in rss_feed
    self.client.rss_add_feed(url=settings.rss_link, item_path="Mikan_RSS")
  File "/src/downloader/qb_downloader.py", line 74, in rss_add_feed
    raise ConflictError()
downloader.exceptions.ConflictError
```

**Comment by EstrellaXD** [comment]
参考 #102
