### ISSUE TITLE
[错误报告]http://host:port/api/v1/data 数据错误

### ISSUE THREAD

**Issue by CatNeverCodes** [EstrellaXD/Auto_Bangumi#120]
### 当前程序版本

2.4.0b4

### 问题类型

程序运行问题

### 问题描述

http://host:port/api/v1/data 无法正确获取数据
日志存在 FileNotFoundError: [Errno 2] No such file or directory: '/config/bangumi.json'
源码 [](https://github.com/EstrellaXD/Auto_Bangumi/blob/main/src/conf/const.py)
line:3 DEFAULT_SETTINGS 存在{"info_path": "/config/bangumi.json"}

手动创建 bangumi.json 并存放 DEFAULT_SETTINGS 值
Docker中手动映射 /config/bangumi.json:/config/bangumi.json 成功解决
并额外显示出订阅番剧列表。

此配置文件无自动生成， 也并未在手把手教程中提及。
修复后仍然无法正常显示正在订阅番剧信息。可能是 WEB 仍在开发原因。

**Comment by EstrellaXD** [comment]
更新一下版本，这个版本不支持 API

**Comment by CatNeverCodes** [comment]
2.5.25-fix 仍然存在此问题。

**Comment by CatNeverCodes** [comment]
> 更新一下版本，这个版本不支持 API

2.5.25-fix 仍存在此问题

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/src/api.py", line 40, in get_data
    data = json_config.load(settings.info_path)
  File "/src/utils/json_config.py", line 6, in load
    with open(filename, "r", encoding="utf-8") as f:
`

**Comment by EstrellaXD** [comment]
彻底删除容器然后重建一下

**Comment by CatNeverCodes** [comment]
> 彻底删除容器然后重建一下

是的，我删除容器，映射文件，甚至镜像。 新拉也是这样。
另外平台是群晖。 或许是 arm 版和 x86 镜像不同原因？
仓也是auto_bangumi，tag latest。
