### ISSUE TITLE
[错误报告]2.5.25无法自动补全番剧 同样的设置 但是2.4.11就可以

### ISSUE THREAD

**Issue by Number-85** [EstrellaXD/Auto_Bangumi#127]
### 当前程序版本

2.5.25

### 问题类型

程序运行问题

### 问题描述

2.5.25无法自动补全番剧 同样的设置 但是2.4.11就可以

### 发生问题时系统日志

```shell
date	stream	content
2022-10-11 02:46:03	stdout	KeyError: 'eps_collect'
2022-10-11 02:46:03	stdout	    if data["eps_collect"]:
2022-10-11 02:46:03	stdout	  File "/src/core/eps_complete.py", line 54, in eps_complete
2022-10-11 02:46:03	stdout	    FullSeasonGet().eps_complete(bangumi_data["bangumi_info"], download_client)
2022-10-11 02:46:03	stdout	  File "/src/app.py", line 74, in main_process
2022-10-11 02:46:03	stdout	    main_process(bangumi_data, download_client)
2022-10-11 02:46:03	stdout	  File "/src/app.py", line 107, in run
2022-10-11 02:46:03	stdout	    run()
2022-10-11 02:46:03	stdout	  File "/src/app.py", line 111, in <module>
2022-10-11 02:46:03	stdout	Traceback (most recent call last):
2022-10-11 02:46:03	stdout	[2022-10-11 10:46:03,898] INFO:     Finished
2022-10-11 02:45:58	stdout	[2022-10-11 10:45:58,892] WARNING:  ERROR with Connection.Please check DNS/Connection settings
2022-10-11 02:45:53	stdout	[2022-10-11 10:45:53,883] WARNING:  ERROR with Connection.Please check DNS/Connection settings
2022-10-11 02:45:48	stdout	[2022-10-11 10:45:48,874] WARNING:  ERROR with Connection.Please check DNS/Connection settings
2022-10-11 02:45:43	stdout	[2022-10-11 10:45:43,864] WARNING:  ERROR with Connection.Please check DNS/Connection settings
2022-10-11 02:45:38	stdout	[2022-10-11 10:45:38,855] WARNING:  ERROR with Connection.Please check DNS/Connection settings
2022-10-11 02:45:38	stdout	[2022-10-11 10:45:38,850] INFO:     Start collecting RSS info.
2022-10-11 02:45:37	stdout	[2022-10-11 10:45:37,714] [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8585[0m (Press CTRL+C to quit)
2022-10-11 02:45:37	stdout	[2022-10-11 10:45:37,713] [32mINFO[0m:     Application startup complete.
2022-10-11 02:45:37	stdout	[2022-10-11 10:45:37,712] [32mINFO[0m:     Waiting for application startup.
2022-10-11 02:45:37	stdout	[2022-10-11 10:45:37,711] [32mINFO[0m:     Started server process [[36m1[0m]
2022-10-11 02:45:36	stdout	[2022-10-11 10:45:36,771] INFO:     RSS Already exists.
2022-10-11 02:45:35	stdout	[2022-10-11 10:45:35,727] INFO:     Starting AutoBangumi...
2022-10-11 02:45:35	stdout	[2022-10-11 10:45:35,726] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
2022-10-11 02:45:35	stdout	[2022-10-11 10:45:35,726] INFO:     Version 2.5.25-fix  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
2022-10-11 02:45:35	stdout	[2022-10-11 10:45:35,726] INFO:                                                |___/                   
2022-10-11 02:45:35	stdout	[2022-10-11 10:45:35,725] INFO:                                                 __/ |                  
2022-10-11 02:45:35	stdout	[2022-10-11 10:45:35,725] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
2022-10-11 02:45:35	stdout	[2022-10-11 10:45:35,725] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
2022-10-11 02:45:35	stdout	[2022-10-11 10:45:35,724] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
2022-10-11 02:45:35	stdout	[2022-10-11 10:45:35,724] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _ 
2022-10-11 02:45:35	stdout	[2022-10-11 10:45:35,723] INFO:          /\        | |      |  _ \                                  (_)
2022-10-11 02:45:35	stdout	[2022-10-11 10:45:35,723] INFO:                     _        ____                                    _ 
2022-10-11 02:45:34	stdout	当前webui为最新版本, 无需更新
2022-10-11 02:45:34	stdout	  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 100  3669  100  3669    0     0   5390      0 --:--:-- --:--:-- --:--:--  5395
2022-10-11 02:45:33	stdout	                                 Dload  Upload   Total   Spent    Left  Speed
2022-10-11 02:45:33	stdout	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2022-10-11 02:45:33	stdout	获取webui最新版本号
```

**Comment by Number-85** [comment]
[bangumi.zip](https://github.com/EstrellaXD/Auto_Bangumi/files/9750687/bangumi.zip)

**Comment by EstrellaXD** [comment]
检查一下过滤器是不是设置太多了

**Comment by Number-85** [comment]
> 

同样的设置2.4.11可以下载

**Comment by czlizy** [comment]
旧版和新版的bangumi_info格式不一样，新版是这样：
`    "bangumi_info": [
        {
            "official_title": "剑风传奇 (1997)",
            "title_raw": "黄金时代篇 MEMORIAL EDITION",
            "season": 1,
            "season_raw": "",
            "group": "Lilith-Raws",
            "dpi": "1080p",
            "source": "Baha",
            "subtitle": "CHT",
            "added": true,
            "eps_collect": true
        }`
找不到"eps_collect"键值跳错了，你把旧版的data文件（bangumi.json）删掉试试
