### ISSUE TITLE
[错误报告]开启AB之后，config目录下的json文件中"bangumi_info"一直为空，QB没有开启下载，QB中RSS订阅规则没有内容

### ISSUE THREAD

**Issue by Number-85** [EstrellaXD/Auto_Bangumi#129]
### 当前程序版本

2.5.25

### 问题类型

程序运行问题

### 问题描述

开启AB之后，config目录下的json文件中"bangumi_info"一直为空，QB没有开启下载，QB中RSS订阅规则没有内容，具体看请看系统日志和配置文件。

### 发生问题时系统日志

[2022-10-13 08:47:42,317] INFO:                     _        ____                                    _ 
[2022-10-13 08:47:42,318] INFO:          /\        | |      |  _ \                                  (_)
[2022-10-13 08:47:42,318] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _ 
[2022-10-13 08:47:42,318] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2022-10-13 08:47:42,319] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2022-10-13 08:47:42,319] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2022-10-13 08:47:42,319] INFO:                                                 __/ |                  
[2022-10-13 08:47:42,320] INFO:                                                |___/                   
[2022-10-13 08:47:42,320] INFO:     Version 2.5.25-fix  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2022-10-13 08:47:42,320] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2022-10-13 08:47:42,321] INFO:     Starting AutoBangumi...
[2022-10-13 08:47:42,628] DEBUG:    Re-initializing context...
[2022-10-13 08:47:42,629] DEBUG:    Re-initializing context...
[2022-10-13 08:47:42,629] DEBUG:    Parsed user URL: ParseResult(scheme='', netloc='192.168.101.12:8989', path='', params='', query='', fragment='')
[2022-10-13 08:47:42,630] DEBUG:    Detecting scheme for URL...
[2022-10-13 08:47:42,637] DEBUG:    Starting new HTTP connection (1): 192.168.101.12:8989
[2022-10-13 08:47:42,641] DEBUG:    http://192.168.101.12:8989 "HEAD / HTTP/1.1" 200 0
[2022-10-13 08:47:42,643] DEBUG:    Using HTTP scheme
[2022-10-13 08:47:42,644] DEBUG:    Base URL: http://192.168.101.12:8989/
[2022-10-13 08:47:42,649] DEBUG:    Starting new HTTP connection (1): 192.168.101.12:8989
[2022-10-13 08:47:43,004] DEBUG:    http://192.168.101.12:8989 "POST /api/v2/auth/login HTTP/1.1" 200 3
[2022-10-13 08:47:43,006] DEBUG:    Login successful
[2022-10-13 08:47:43,007] DEBUG:    SID: 4vTI5zcbrN3I5zxdazB+uyk25E8pu2xC
[2022-10-13 08:47:43,014] DEBUG:    http://192.168.101.12:8989 "POST /api/v2/app/setPreferences HTTP/1.1" 200 0
[2022-10-13 08:47:43,021] DEBUG:    http://192.168.101.12:8989 "GET /api/v2/rss/items HTTP/1.1" 200 159
[2022-10-13 08:47:43,023] INFO:     RSS Already exists.
[2022-10-13 08:47:43,031] DEBUG:    http://192.168.101.12:8989 "POST /api/v2/torrents/info HTTP/1.1" 200 2
[2022-10-13 08:47:43,033] INFO:     Start collecting RSS info.
[2022-10-13 08:47:43,037] DEBUG:    Starting new HTTPS connection (1): mikanani.me:443
[2022-10-13 08:47:43,039] DEBUG:    URL: https://mikanani.me/RSS/MyBangumi?token=aZl1qJLptEM2nmS4ssn7tC8eNp0R5XTs6Qkwsr0d%2bi4%3d
[2022-10-13 08:47:43,039] DEBUG:    HTTPSConnectionPool(host='mikanani.me', port=443): Max retries exceeded with url: /RSS/MyBangumi?token=aZl1qJLptEM2nmS4ssn7tC8eNp0R5XTs6Qkwsr0d%2Bi4%3D (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[2022-10-13 08:47:43,040] WARNING:  ERROR with Connection.Please check DNS/Connection settings
[2022-10-13 08:47:48,048] DEBUG:    Starting new HTTPS connection (2): mikanani.me:443
[2022-10-13 08:47:48,049] DEBUG:    URL: https://mikanani.me/RSS/MyBangumi?token=aZl1qJLptEM2nmS4ssn7tC8eNp0R5XTs6Qkwsr0d%2bi4%3d
[2022-10-13 08:47:48,049] DEBUG:    HTTPSConnectionPool(host='mikanani.me', port=443): Max retries exceeded with url: /RSS/MyBangumi?token=aZl1qJLptEM2nmS4ssn7tC8eNp0R5XTs6Qkwsr0d%2Bi4%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
[2022-10-13 08:47:48,050] WARNING:  ERROR with Connection.Please check DNS/Connection settings
[2022-10-13 08:47:53,056] DEBUG:    Starting new HTTPS connection (3): mikanani.me:443
[2022-10-13 08:47:53,057] DEBUG:    URL: https://mikanani.me/RSS/MyBangumi?token=aZl1qJLptEM2nmS4ssn7tC8eNp0R5XTs6Qkwsr0d%2bi4%3d
[2022-10-13 08:47:53,058] DEBUG:    HTTPSConnectionPool(host='mikanani.me', port=443): Max retries exceeded with url: /RSS/MyBangumi?token=aZl1qJLptEM2nmS4ssn7tC8eNp0R5XTs6Qkwsr0d%2Bi4%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
[2022-10-13 08:47:53,058] WARNING:  ERROR with Connection.Please check DNS/Connection settings
[2022-10-13 08:47:58,065] DEBUG:    Starting new HTTPS connection (4): mikanani.me:443
[2022-10-13 08:47:58,067] DEBUG:    URL: https://mikanani.me/RSS/MyBangumi?token=aZl1qJLptEM2nmS4ssn7tC8eNp0R5XTs6Qkwsr0d%2bi4%3d
[2022-10-13 08:47:58,067] DEBUG:    HTTPSConnectionPool(host='mikanani.me', port=443): Max retries exceeded with url: /RSS/MyBangumi?token=aZl1qJLptEM2nmS4ssn7tC8eNp0R5XTs6Qkwsr0d%2Bi4%3D (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[2022-10-13 08:47:58,067] WARNING:  ERROR with Connection.Please check DNS/Connection settings
[2022-10-13 08:48:03,075] DEBUG:    Starting new HTTPS connection (5): mikanani.me:443
[2022-10-13 08:48:03,077] DEBUG:    URL: https://mikanani.me/RSS/MyBangumi?token=aZl1qJLptEM2nmS4ssn7tC8eNp0R5XTs6Qkwsr0d%2bi4%3d
[2022-10-13 08:48:03,077] DEBUG:    HTTPSConnectionPool(host='mikanani.me', port=443): Max retries exceeded with url: /RSS/MyBangumi?token=aZl1qJLptEM2nmS4ssn7tC8eNp0R5XTs6Qkwsr0d%2Bi4%3D (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
[2022-10-13 08:48:03,077] WARNING:  ERROR with Connection.Please check DNS/Connection settings
[2022-10-13 08:48:08,082] DEBUG:    'NoneType' object has no attribute 'text'
[2022-10-13 08:48:08,082] INFO:     Finished
[2022-10-13 08:48:08,083] INFO:     Running....
[2022-10-13 08:48:08,084] DEBUG:    Saved
[2022-10-13 08:48:08,088] DEBUG:    Resetting dropped connection: 192.168.101.12
[2022-10-13 08:48:08,091] DEBUG:    http://192.168.101.12:8989 "POST /api/v2/torrents/info HTTP/1.1" 200 2
[2022-10-13 08:48:08,093] DEBUG:    Checked 0 files
[2022-10-13 08:49:08,156] DEBUG:    Resetting dropped connection: 192.168.101.12
[2022-10-13 08:49:08,160] DEBUG:    http://192.168.101.12:8989 "POST /api/v2/torrents/info HTTP/1.1" 200 2
[2022-10-13 08:49:08,161] DEBUG:    Checked 0 files

**Comment by Number-85** [comment]
[bangumi.zip](https://github.com/EstrellaXD/Auto_Bangumi/files/9763836/bangumi.zip)
配置文件

**Comment by EstrellaXD** [comment]
看起来是链接蜜柑计划出现了问题，请检查网络连接

**Comment by Number-85** [comment]
> 看起来是链接蜜柑计划出现了问题，请检查网络连接

已经挂了梯子了，并且同等网络环境下，可是我用2.4.11就能下载，2.5.X都不行，我现在解决方案装两个AD，分两个config，用2.4.11解析导入下载，2.5.25来改名

**Comment by Number-85** [comment]
这个是2.5.25关了梯子后的日志文件
2022-10-14 08:23:21	stdout	FileNotFoundError: [Errno 2] No such file or directory: '/config/bangumi.json'
2022-10-14 08:23:21	stdout	    with open(filename, "r", encoding="utf-8") as f:
2022-10-14 08:23:21	stdout	  File "/src/utils/json_config.py", line 6, in load
2022-10-14 08:23:21	stdout	    data = json_config.load(settings.info_path)
2022-10-14 08:23:21	stdout	  File "/src/api.py", line 40, in get_data
2022-10-14 08:23:21	stdout	    result = context.run(func, *args)
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2022-10-14 08:23:21	stdout	    return await future
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2022-10-14 08:23:21	stdout	    return await get_asynclib().run_sync_in_worker_thread(
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2022-10-14 08:23:21	stdout	    return await anyio.to_thread.run_sync(func, *args)
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2022-10-14 08:23:21	stdout	    return await run_in_threadpool(dependant.call, **values)
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
2022-10-14 08:23:21	stdout	    raw_response = await run_endpoint_function(
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
2022-10-14 08:23:21	stdout	    response = await func(request)
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
2022-10-14 08:23:21	stdout	    await self.app(scope, receive, send)
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
2022-10-14 08:23:21	stdout	    await route.handle(scope, receive, send)
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
2022-10-14 08:23:21	stdout	    await self.app(scope, receive, send)
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2022-10-14 08:23:21	stdout	    raise e
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2022-10-14 08:23:21	stdout	    await self.app(scope, receive, sender)
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
2022-10-14 08:23:21	stdout	    raise exc
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
2022-10-14 08:23:21	stdout	    await self.app(scope, receive, _send)
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2022-10-14 08:23:21	stdout	    raise exc
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2022-10-14 08:23:21	stdout	    await self.middleware_stack(scope, receive, send)
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
2022-10-14 08:23:21	stdout	    await super().__call__(scope, receive, send)
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
2022-10-14 08:23:21	stdout	    return await self.app(scope, receive, send)
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2022-10-14 08:23:21	stdout	    result = await app(  # type: ignore[func-returns-value]
2022-10-14 08:23:21	stdout	  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
2022-10-14 08:23:21	stdout	Traceback (most recent call last):
2022-10-14 08:23:21	stdout	[2022-10-14 16:23:21,367] [31mERROR[0m:    Exception in ASGI application
2022-10-14 08:23:21	stdout	[32mINFO[0m:     172.17.0.1:47532 - "[1mGET /api/v1/data HTTP/1.1[0m" [91m500 Internal Server Error[0m
2022-10-14 08:23:21	stdout	[2022-10-14 16:23:21,084] WARNING:  ERROR with Connection.Please check DNS/Connection settings
2022-10-14 08:23:21	stdout	[32mINFO[0m:     172.17.0.1:47532 - "[1mGET / HTTP/1.1[0m" [32m200 OK[0m
2022-10-14 08:23:20	stdout	FileNotFoundError: [Errno 2] No such file or directory: '/config/bangumi.json'
2022-10-14 08:23:20	stdout	    with open(filename, "r", encoding="utf-8") as f:
2022-10-14 08:23:20	stdout	  File "/src/utils/json_config.py", line 6, in load
2022-10-14 08:23:20	stdout	    data = json_config.load(settings.info_path)
2022-10-14 08:23:20	stdout	  File "/src/api.py", line 40, in get_data
2022-10-14 08:23:20	stdout	    result = context.run(func, *args)
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2022-10-14 08:23:20	stdout	    return await future
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2022-10-14 08:23:20	stdout	    return await get_asynclib().run_sync_in_worker_thread(
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2022-10-14 08:23:20	stdout	    return await anyio.to_thread.run_sync(func, *args)
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2022-10-14 08:23:20	stdout	    return await run_in_threadpool(dependant.call, **values)
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
2022-10-14 08:23:20	stdout	    raw_response = await run_endpoint_function(
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
2022-10-14 08:23:20	stdout	    response = await func(request)
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
2022-10-14 08:23:20	stdout	    await self.app(scope, receive, send)
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
2022-10-14 08:23:20	stdout	    await route.handle(scope, receive, send)
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
2022-10-14 08:23:20	stdout	    await self.app(scope, receive, send)
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2022-10-14 08:23:20	stdout	    raise e
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2022-10-14 08:23:20	stdout	    await self.app(scope, receive, sender)
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
2022-10-14 08:23:20	stdout	    raise exc
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
2022-10-14 08:23:20	stdout	    await self.app(scope, receive, _send)
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2022-10-14 08:23:20	stdout	    raise exc
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2022-10-14 08:23:20	stdout	    await self.middleware_stack(scope, receive, send)
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
2022-10-14 08:23:20	stdout	    await super().__call__(scope, receive, send)
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
2022-10-14 08:23:20	stdout	    return await self.app(scope, receive, send)
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2022-10-14 08:23:20	stdout	    result = await app(  # type: ignore[func-returns-value]
2022-10-14 08:23:20	stdout	  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
2022-10-14 08:23:20	stdout	Traceback (most recent call last):
2022-10-14 08:23:20	stdout	[2022-10-14 16:23:19,982] [31mERROR[0m:    Exception in ASGI application
2022-10-14 08:23:19	stdout	[32mINFO[0m:     172.17.0.1:47530 - "[1mGET /api/v1/data HTTP/1.1[0m" [91m500 Internal Server Error[0m
2022-10-14 08:21:13	stdout	[2022-10-14 16:21:13,009] [32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8585[0m (Press CTRL+C to quit)
2022-10-14 08:21:13	stdout	[2022-10-14 16:21:13,008] [32mINFO[0m:     Application startup complete.
2022-10-14 08:21:13	stdout	[2022-10-14 16:21:13,007] [32mINFO[0m:     Waiting for application startup.
2022-10-14 08:21:13	stdout	[2022-10-14 16:21:13,006] [32mINFO[0m:     Started server process [[36m1[0m]
2022-10-14 08:21:12	stdout	[2022-10-14 16:21:12,408] INFO:     Start collecting RSS info.
2022-10-14 08:21:12	stdout	[2022-10-14 16:21:12,406] INFO:     Building data information...
2022-10-14 08:21:12	stdout	[2022-10-14 16:21:12,406] INFO:     RSS Already exists.
2022-10-14 08:21:11	stdout	[2022-10-14 16:21:11,240] INFO:     Starting AutoBangumi...
2022-10-14 08:21:11	stdout	[2022-10-14 16:21:11,240] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
2022-10-14 08:21:11	stdout	[2022-10-14 16:21:11,239] INFO:     Version 2.5.25-fix  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
2022-10-14 08:21:11	stdout	[2022-10-14 16:21:11,239] INFO:                                                |___/                   
2022-10-14 08:21:11	stdout	[2022-10-14 16:21:11,239] INFO:                                                 __/ |                  
2022-10-14 08:21:11	stdout	[2022-10-14 16:21:11,238] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
2022-10-14 08:21:11	stdout	[2022-10-14 16:21:11,238] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
2022-10-14 08:21:11	stdout	[2022-10-14 16:21:11,237] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
2022-10-14 08:21:11	stdout	[2022-10-14 16:21:11,237] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _ 
2022-10-14 08:21:11	stdout	[2022-10-14 16:21:11,236] INFO:          /\        | |      |  _ \                                  (_)
2022-10-14 08:21:11	stdout	[2022-10-14 16:21:11,236] INFO:                     _        ____                                    _ 
2022-10-14 08:21:08	stdout	webui下载完成
2022-10-14 08:21:08	stdout	  inflating: dist/robots.txt
2022-10-14 08:21:08	stdout	  inflating: dist/index.html
2022-10-14 08:21:08	stdout	  inflating: dist/assets/el-popper.188d4bcb.js
2022-10-14 08:21:08	stdout	  inflating: dist/assets/index.70730466.css
2022-10-14 08:21:08	stdout	  inflating: dist/assets/logo.b7d483a4.png
2022-10-14 08:21:08	stdout	  inflating: dist/assets/index.aafefea2.js
2022-10-14 08:21:08	stdout	  inflating: dist/assets/YLayout.7d7a1595.js
2022-10-14 08:21:08	stdout	  inflating: dist/assets/index.aafd5d08.js
2022-10-14 08:21:08	stdout	  inflating: dist/assets/el-button.2fb03e61.js
2022-10-14 08:21:08	stdout	  inflating: dist/assets/index.a44b6412.css
2022-10-14 08:21:08	stdout	  inflating: dist/assets/index.1d3bc1da.js
2022-10-14 08:21:08	stdout	  inflating: dist/assets/index.1a7b13ed.css
2022-10-14 08:21:08	stdout	  inflating: dist/assets/index.d2c24fae.js
2022-10-14 08:21:08	stdout	  inflating: dist/assets/el-popper.f394526f.css
2022-10-14 08:21:08	stdout	  inflating: dist/assets/YLayout.909c574a.css
2022-10-14 08:21:08	stdout	  inflating: dist/assets/debug.053ff9e4.js
2022-10-14 08:21:08	stdout	  inflating: dist/assets/index.a6639e6c.css
2022-10-14 08:21:08	stdout	  inflating: dist/assets/index.0be127ec.js
2022-10-14 08:21:08	stdout	  inflating: dist/assets/index.12f8f260.js
2022-10-14 08:21:08	stdout	  inflating: dist/assets/el-button.170410e4.css
2022-10-14 08:21:08	stdout	   creating: dist/assets/
2022-10-14 08:21:08	stdout	  inflating: dist/favicon.ico
2022-10-14 08:21:08	stdout	   creating: dist/
2022-10-14 08:21:08	stdout	Archive:  ./dist.zip
2022-10-14 08:21:08	stdout	'dist.zip' saved
2022-10-14 08:21:08	stdout	dist.zip              32% |**********                      | 64754  0:00:02 ETA dist.zip             100% |********************************|  193k  0:00:00 ETA
2022-10-14 08:21:07	stdout	saving to 'dist.zip'
2022-10-14 08:21:05	stdout	Connecting to ghproxy.com (138.2.88.86:443)
2022-10-14 08:21:05	stdout	准备下载最新版本webui
2022-10-14 08:21:05	stdout	  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 100  3669  100  3669    0     0   5623      0 --:--:-- --:--:-- --:--:--  5618 100  3669  100  3669    0     0   5607      0 --:--:-- --:--:-- --:--:--  5601
2022-10-14 08:21:04	stdout	                                 Dload  Upload   Total   Spent    Left  Speed
2022-10-14 08:21:04	stdout	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2022-10-14 08:21:04	stdout	获取webui最新版本号
