### ISSUE TITLE
[错误报告]该 RSS 项的路径已存在：Mikan_RSS

### ISSUE THREAD

**Issue by iRinwind** [EstrellaXD/Auto_Bangumi#133]
### 当前程序版本

2.5.25

### 问题类型

程序运行问题

### 问题描述

在 macos 上使用 docker for desktop 进行配置。qb 运行正常，但是 ab 的 webUI 看不到RSS订阅，订阅地址已填。
注意到报错里有一条[2022-10-29 17:06:07,172] ERROR     该 RSS 项的路径已存在：Mikan_RSS。 

新手，平时用 mac mini 上跑的 plex server 当媒体服务器，尝试使用 ab 希望能帮忙看看，谢谢！

### 发生问题时系统日志

```shell
[2022-10-29 17:06:06,971] INFO:                     _        ____                                    _ 
[2022-10-29 17:06:06,972] INFO:          /\        | |      |  _ \                                  (_)
[2022-10-29 17:06:06,973] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _ 
[2022-10-29 17:06:06,974] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2022-10-29 17:06:06,976] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2022-10-29 17:06:06,978] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2022-10-29 17:06:06,979] INFO:                                                 __/ |                  
[2022-10-29 17:06:06,980] INFO:                                                |___/                   
[2022-10-29 17:06:06,981] INFO:     Version 2.5.25-fix  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2022-10-29 17:06:06,983] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2022-10-29 17:06:06,985] INFO:     Starting AutoBangumi...
[2022-10-29 17:06:07,167] INFO:     No feed exists, start adding feed.
[2022-10-29 17:06:07,172] ERROR     该 RSS 项的路径已存在：Mikan_RSS。
Traceback (most recent call last):
  File "/src/downloader/qb_downloader.py", line 71, in rss_add_feed
    self._client.rss_add_feed(url, item_path)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/decorators.py", line 92, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/rss.py", line 174, in rss_add_feed
    self._post(_name=APINames.RSS, _method="addFeed", data=data, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 350, in _post
    return self._request_manager(
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 401, in _request_manager
    return self._request(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 463, in _request
    self._handle_error_responses(data, params, response)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/request.py", line 664, in _handle_error_responses
    raise Conflict409Error(response.text)
qbittorrentapi.exceptions.Conflict409Error: 该 RSS 项的路径已存在：Mikan_RSS。
```

**Comment by wmyfelix** [comment]
删除qBittorrent的Mikan_RSS。

**Comment by EstrellaXD** [comment]
删除原本的 RSS 订阅再尝试运行一次
