### ISSUE TITLE
[错误报告]规则存在中文时报错

### ISSUE THREAD

**Issue by mikusaa** [EstrellaXD/Auto_Bangumi#187]
### 当前程序版本

2.6.0-beta5

### 问题类型

程序运行问题

### 问题描述

当规则存在中文时，即报错
```
        "filter": [
            "720",
            "\\d+-\\d+",
            "BIG5",
            "CHT",
            "JPTC",
            "\繁日双语\",
            "\繁体\",
            "\内嵌\"
```

### 发生问题时系统日志

```shell
Traceback (most recent call last):
  File "/app/main.py", line 1, in <module>
    from module import app
  File "/app/module/app.py", line 5, in <module>
    from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, VERSION
  File "/app/module/conf/__init__.py", line 1, in <module>
    from .log import setup_logger, LOG_PATH
  File "/app/module/conf/log.py", line 3, in <module>
    from .config import settings
  File "/app/module/conf/config.py", line 73, in <module>
    settings = Settings(CONFIG_PATH)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/conf/config.py", line 33, in __init__
    self.load(path)
  File "/app/module/conf/config.py", line 40, in load
    conf = json.load(f)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 673: invalid start byte
Traceback (most recent call last):
  File "/app/main.py", line 1, in <module>
    from module import app
  File "/app/module/app.py", line 5, in <module>
    from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, VERSION
  File "/app/module/conf/__init__.py", line 1, in <module>
    from .log import setup_logger, LOG_PATH
  File "/app/module/conf/log.py", line 3, in <module>
    from .config import settings
  File "/app/module/conf/config.py", line 73, in <module>
    settings = Settings(CONFIG_PATH)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/conf/config.py", line 33, in __init__
    self.load(path)
  File "/app/module/conf/config.py", line 40, in load
    conf = json.load(f)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 674: invalid start byte
```

**Comment by mikusaa** [comment]
已经自己好了的样子（
