### ISSUE TITLE
[错误报告] log报错AttributeError: 'AttrDict' instance has no attribute 'url'

### ISSUE THREAD

**Issue by nicosuki123** [EstrellaXD/Auto_Bangumi#222]
### 当前程序版本

2.6.3

### 问题类型

WebUI

### 问题描述

镜像是重新拉的，没有使用老版本的环境变量，全部从web配置，更新版本后出现以下报错信息，qb从AB不能正常更新rss

### 发生问题时系统日志

```shell
[2023-04-30 09:58:01,832] INFO:                     _        ____                                    _
[2023-04-30 09:58:01,833] INFO:          /\        | |      |  _ \                                  (_)
[2023-04-30 09:58:01,833] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _
[2023-04-30 09:58:01,833] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2023-04-30 09:58:01,833] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2023-04-30 09:58:01,833] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2023-04-30 09:58:01,833] INFO:                                                 __/ |
[2023-04-30 09:58:01,833] INFO:                                                |___/
[2023-04-30 09:58:01,834] INFO:     Version 2.6.3  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2023-04-30 09:58:01,834] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2023-04-30 09:58:01,834] INFO:     Starting AutoBangumi...
[2023-04-30 09:58:01,860] INFO      Started server process [78]
[2023-04-30 09:58:01,861] INFO      Waiting for application startup.
[2023-04-30 09:58:01,861] INFO      Application startup complete.
[2023-04-30 09:58:01,862] INFO      Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
[2023-04-30 09:58:02,025] WARNING:  Cannot add new category, maybe already exists.
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/app.py", line 79, in run
    download_client.rss_feed(rss_link)
  File "/app/module/core/download_client.py", line 72, in rss_feed
    if self.client.get_rss_info(rss_link):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/downloader/qb_downloader.py", line 72, in get_rss_info
    if item[1].url == url:
       ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/_attrdict.py", line 147, in __getattr__
    raise AttributeError(
AttributeError: 'AttrDict' instance has no attribute 'url'
```

**Comment by EstrellaXD** [comment]
#221

**Comment by nicosuki123** [comment]
重新编辑了一下问题描述

**Comment by EstrellaXD** [comment]
qb 版本是？

**Comment by nicosuki123** [comment]
qb 从4.3.9更新到了4.5.3，还是相同的报错

**Comment by LIGHT1213** [comment]
我也遇到了类似的问题
#软件版本如下
两个软件版本如下
![bug](https://raw.githubusercontent.com/LIGHT1213/picture/master/auto%E7%89%88%E6%9C%AC.png)  
![bug](https://raw.githubusercontent.com/LIGHT1213/picture/master/qb%E7%89%88%E6%9C%AC.png)  
#日志如下  
```2023-05-02 20:09:51,626] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2023-05-02 20:09:51,626] INFO:     Starting AutoBangumi...
[2023-05-02 20:09:51,828] INFO      Started server process [77]
[2023-05-02 20:09:51,839] INFO      Waiting for application startup.
[2023-05-02 20:09:51,842] INFO      Application startup complete.
[2023-05-02 20:09:51,864] INFO      Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
[2023-05-02 20:09:52,466] WARNING:  Cannot add new category, maybe already exists.
[2023-05-02 20:09:52,483] INFO:     No feed exists, start adding feed.
[2023-05-02 20:09:52,512] ERROR     RSS Exist.
Traceback (most recent call last):
  File "/app/module/downloader/qb_downloader.py", line 81, in rss_add_feed
    self._client.rss_add_feed(url, item_path)
  File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 92, in wrapper
    return func(client, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/rss.py", line 176, in rss_add_feed
    self._post(_name=APINames.RSS, _method="addFeed", data=data, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 390, in _post
    return self._request_manager(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 466, in _request_manager
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 543, in _request
    self._handle_error_responses(data, params, response)
  File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/request.py", line 784, in _handle_error_responses
    raise Conflict409Error(response.text)
qbittorrentapi.exceptions.Conflict409Error: 该 RSS 项的路径已存在：Mikan_RSS。
[2023-05-02 20:09:52,515] INFO:     Add RSS Feed successfully.
[2023-05-02 20:09:52,521] INFO:     Data file loaded
[2023-05-02 20:09:52,528] INFO:     Start collecting RSS info.
```   
有趣的是每次重启docker之后订阅番剧里面的某一部会多出一行如下图  
![bug](https://raw.githubusercontent.com/LIGHT1213/picture/master/bug1.png)
