### ISSUE TITLE
[错误报告] 安装后无法进入webUI

### ISSUE THREAD

**Issue by shchin98** [EstrellaXD/Auto_Bangumi#225]
### 当前程序版本

2.6.3

### 问题类型

WebUI

### 问题描述

通过docker compose安装后出错，无法进行webUI

```yaml  
auto_bangumi:
    container_name: AutoBangumi
    environment:
      - TZ=Etc/UTC
      - PGID=1000
      - PUID=1000
      - AB_INTERVAL_TIME=1800
      - AB_DOWNLOADER_HOST=qbittorrent:8989
      - AB_DOWNLOADER_USERNAME=admin
      - AB_DOWNLOADER_PASSWORD=adminadmin
      - AB_METHOD=pn
      - AB_GROUP_TAG=True
      - AB_NOT_CONTAIN=720
      - AB_DOWNLOAD_PATH=/downloads/Bangumi
      - AB_RSS=${RSS}
      - AB_DEBUG_MODE=False
      - AB_EP_COMPLETE=False
      - AB_SEASON_ONE=True
    networks:
      - auto_bangumi
    volumes:
      - auto_bangumi:/config
    ports:
      - 7892:7892
    dns:
      - 8.8.8.8
      - 223.5.5.5
    restart: unless-stopped
    image: estrellaxd/auto_bangumi:latest
    depends_on:
      - qbittorrent

networks:
  auto_bangumi:

volumes:
  qb_config:
    external: false
  auto_bangumi:
    external: false
```

### 发生问题时系统日志

```shell
2023-05-01 00:51:08 s6-rc: info: service s6rc-oneshot-runner: starting
2023-05-01 00:51:08 s6-rc: info: service s6rc-oneshot-runner successfully started
2023-05-01 00:51:08 s6-rc: info: service fix-attrs: starting
2023-05-01 00:51:08 s6-rc: info: service fix-attrs successfully started
2023-05-01 00:51:08 s6-rc: info: service legacy-cont-init: starting
2023-05-01 00:51:08 cont-init: info: running /etc/cont-init.d/010-old-compatible
2023-05-01 00:51:08 cont-init: info: /etc/cont-init.d/010-old-compatible exited 0
2023-05-01 00:51:08 cont-init: info: running /etc/cont-init.d/020-fixuser
2023-05-01 00:51:09 cont-init: info: /etc/cont-init.d/020-fixuser exited 0
2023-05-01 00:51:09 s6-rc: info: service legacy-cont-init successfully started
2023-05-01 00:51:09 s6-rc: info: service legacy-services: starting
2023-05-01 00:51:09 services-up: info: copying legacy longrun auto_bangumi (no readiness notification)
2023-05-01 00:51:09 s6-rc: info: service legacy-services successfully started
2023-05-01 00:51:09 Traceback (most recent call last):
2023-05-01 00:51:09   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:09     from module import app
2023-05-01 00:51:09   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:09     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:09   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:09     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:09   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:09     from .config import settings
2023-05-01 00:51:09   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:09     settings = env_to_config()
2023-05-01 00:51:09                ^^^^^^^^^^^^^^^
2023-05-01 00:51:09   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:09     return Setting(**_settings)
2023-05-01 00:51:09            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:09   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:09 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:09 rss_parser -> token
2023-05-01 00:51:09   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:10 Traceback (most recent call last):
2023-05-01 00:51:10   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:10     from module import app
2023-05-01 00:51:10   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:10     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:10   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:10     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:10   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:10     from .config import settings
2023-05-01 00:51:10   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:10     settings = env_to_config()
2023-05-01 00:51:10                ^^^^^^^^^^^^^^^
2023-05-01 00:51:10   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:10     return Setting(**_settings)
2023-05-01 00:51:10            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:10   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:10 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:10 rss_parser -> token
2023-05-01 00:51:10   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:11 Traceback (most recent call last):
2023-05-01 00:51:11   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:11     from module import app
2023-05-01 00:51:11   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:11     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:11   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:11     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:11   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:11     from .config import settings
2023-05-01 00:51:11   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:11     settings = env_to_config()
2023-05-01 00:51:11                ^^^^^^^^^^^^^^^
2023-05-01 00:51:11   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:11     return Setting(**_settings)
2023-05-01 00:51:11            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:11   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:11 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:11 rss_parser -> token
2023-05-01 00:51:11   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:12 Traceback (most recent call last):
2023-05-01 00:51:12   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:12     from module import app
2023-05-01 00:51:12   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:12     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:12   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:12     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:12   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:12     from .config import settings
2023-05-01 00:51:12   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:12     settings = env_to_config()
2023-05-01 00:51:12                ^^^^^^^^^^^^^^^
2023-05-01 00:51:12   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:12     return Setting(**_settings)
2023-05-01 00:51:12            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:12   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:12 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:12 rss_parser -> token
2023-05-01 00:51:12   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:13 Traceback (most recent call last):
2023-05-01 00:51:13   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:13     from module import app
2023-05-01 00:51:13   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:13     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:13   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:13     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:13   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:13     from .config import settings
2023-05-01 00:51:13   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:13     settings = env_to_config()
2023-05-01 00:51:13                ^^^^^^^^^^^^^^^
2023-05-01 00:51:13   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:13     return Setting(**_settings)
2023-05-01 00:51:13            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:13   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:13 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:13 rss_parser -> token
2023-05-01 00:51:13   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:14 Traceback (most recent call last):
2023-05-01 00:51:14   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:14     from module import app
2023-05-01 00:51:14   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:14     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:14   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:14     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:14   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:14     from .config import settings
2023-05-01 00:51:14   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:14     settings = env_to_config()
2023-05-01 00:51:14                ^^^^^^^^^^^^^^^
2023-05-01 00:51:14   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:14     return Setting(**_settings)
2023-05-01 00:51:14            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:14   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:14 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:14 rss_parser -> token
2023-05-01 00:51:14   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:15 Traceback (most recent call last):
2023-05-01 00:51:15   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:15     from module import app
2023-05-01 00:51:15   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:15     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:15   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:15     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:15   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:15     from .config import settings
2023-05-01 00:51:15   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:15     settings = env_to_config()
2023-05-01 00:51:15                ^^^^^^^^^^^^^^^
2023-05-01 00:51:15   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:15     return Setting(**_settings)
2023-05-01 00:51:15            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:15   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:15 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:15 rss_parser -> token
2023-05-01 00:51:15   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:16 Traceback (most recent call last):
2023-05-01 00:51:16   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:16     from module import app
2023-05-01 00:51:16   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:16     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:16   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:16     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:16   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:16     from .config import settings
2023-05-01 00:51:16   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:16     settings = env_to_config()
2023-05-01 00:51:16                ^^^^^^^^^^^^^^^
2023-05-01 00:51:16   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:16     return Setting(**_settings)
2023-05-01 00:51:16            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:16   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:16 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:16 rss_parser -> token
2023-05-01 00:51:16   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:17 Traceback (most recent call last):
2023-05-01 00:51:17   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:17     from module import app
2023-05-01 00:51:17   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:17     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:17   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:17     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:17   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:17     from .config import settings
2023-05-01 00:51:17   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:17     settings = env_to_config()
2023-05-01 00:51:17                ^^^^^^^^^^^^^^^
2023-05-01 00:51:17   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:17     return Setting(**_settings)
2023-05-01 00:51:17            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:17   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:17 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:17 rss_parser -> token
2023-05-01 00:51:17   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:18 Traceback (most recent call last):
2023-05-01 00:51:18   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:18     from module import app
2023-05-01 00:51:18   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:18     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:18   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:18     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:18   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:18     from .config import settings
2023-05-01 00:51:18   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:18     settings = env_to_config()
2023-05-01 00:51:18                ^^^^^^^^^^^^^^^
2023-05-01 00:51:18   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:18     return Setting(**_settings)
2023-05-01 00:51:18            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:18   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:18 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:18 rss_parser -> token
2023-05-01 00:51:18   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:19 Traceback (most recent call last):
2023-05-01 00:51:19   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:19     from module import app
2023-05-01 00:51:19   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:19     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:19   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:19     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:19   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:19     from .config import settings
2023-05-01 00:51:19   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:19     settings = env_to_config()
2023-05-01 00:51:19                ^^^^^^^^^^^^^^^
2023-05-01 00:51:19   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:19     return Setting(**_settings)
2023-05-01 00:51:19            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:19   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:19 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:19 rss_parser -> token
2023-05-01 00:51:19   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:20 Traceback (most recent call last):
2023-05-01 00:51:20   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:20     from module import app
2023-05-01 00:51:20   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:20     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:20   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:20     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:20   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:20     from .config import settings
2023-05-01 00:51:20   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:20     settings = env_to_config()
2023-05-01 00:51:20                ^^^^^^^^^^^^^^^
2023-05-01 00:51:20   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:20     return Setting(**_settings)
2023-05-01 00:51:20            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:20   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:20 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:20 rss_parser -> token
2023-05-01 00:51:20   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:21 Traceback (most recent call last):
2023-05-01 00:51:21   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:21     from module import app
2023-05-01 00:51:21   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:21     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:21   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:21     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:21   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:21     from .config import settings
2023-05-01 00:51:21   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:21     settings = env_to_config()
2023-05-01 00:51:21                ^^^^^^^^^^^^^^^
2023-05-01 00:51:21   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:21     return Setting(**_settings)
2023-05-01 00:51:21            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:21   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:21 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:21 rss_parser -> token
2023-05-01 00:51:21   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:22 Traceback (most recent call last):
2023-05-01 00:51:22   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:22     from module import app
2023-05-01 00:51:22   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:22     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:22   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:22     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:22   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:22     from .config import settings
2023-05-01 00:51:22   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:22     settings = env_to_config()
2023-05-01 00:51:22                ^^^^^^^^^^^^^^^
2023-05-01 00:51:22   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:22     return Setting(**_settings)
2023-05-01 00:51:22            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:22   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:22 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:22 rss_parser -> token
2023-05-01 00:51:22   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:23 Traceback (most recent call last):
2023-05-01 00:51:23   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:23     from module import app
2023-05-01 00:51:23   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:23     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:23   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:23     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:23   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:23     from .config import settings
2023-05-01 00:51:23   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:23     settings = env_to_config()
2023-05-01 00:51:23                ^^^^^^^^^^^^^^^
2023-05-01 00:51:23   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:23     return Setting(**_settings)
2023-05-01 00:51:23            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:23   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:23 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:23 rss_parser -> token
2023-05-01 00:51:23   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:24 Traceback (most recent call last):
2023-05-01 00:51:24   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:24     from module import app
2023-05-01 00:51:24   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:24     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:24   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:24     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:24   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:24     from .config import settings
2023-05-01 00:51:24   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:24     settings = env_to_config()
2023-05-01 00:51:24                ^^^^^^^^^^^^^^^
2023-05-01 00:51:24   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:24     return Setting(**_settings)
2023-05-01 00:51:24            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:24   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:24 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:24 rss_parser -> token
2023-05-01 00:51:24   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:25 Traceback (most recent call last):
2023-05-01 00:51:25   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:25     from module import app
2023-05-01 00:51:25   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:25     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:25   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:25     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:25   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:25     from .config import settings
2023-05-01 00:51:25   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:25     settings = env_to_config()
2023-05-01 00:51:25                ^^^^^^^^^^^^^^^
2023-05-01 00:51:25   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:25     return Setting(**_settings)
2023-05-01 00:51:25            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:25   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:25 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:25 rss_parser -> token
2023-05-01 00:51:25   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:26 Traceback (most recent call last):
2023-05-01 00:51:26   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:26     from module import app
2023-05-01 00:51:26   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:26     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:26   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:26     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:26   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:26     from .config import settings
2023-05-01 00:51:26   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:26     settings = env_to_config()
2023-05-01 00:51:26                ^^^^^^^^^^^^^^^
2023-05-01 00:51:26   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:26     return Setting(**_settings)
2023-05-01 00:51:26            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:26   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:26 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:26 rss_parser -> token
2023-05-01 00:51:26   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:27 Traceback (most recent call last):
2023-05-01 00:51:27   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:27     from module import app
2023-05-01 00:51:27   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:27     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:27   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:27     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:27   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:27     from .config import settings
2023-05-01 00:51:27   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:27     settings = env_to_config()
2023-05-01 00:51:27                ^^^^^^^^^^^^^^^
2023-05-01 00:51:27   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:27     return Setting(**_settings)
2023-05-01 00:51:27            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:27   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:27 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:27 rss_parser -> token
2023-05-01 00:51:27   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:28 Traceback (most recent call last):
2023-05-01 00:51:28   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:28     from module import app
2023-05-01 00:51:28   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:28     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:28   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:28     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:28   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:28     from .config import settings
2023-05-01 00:51:28   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:28     settings = env_to_config()
2023-05-01 00:51:28                ^^^^^^^^^^^^^^^
2023-05-01 00:51:28   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:28     return Setting(**_settings)
2023-05-01 00:51:28            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:28   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:28 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:28 rss_parser -> token
2023-05-01 00:51:28   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:29 Traceback (most recent call last):
2023-05-01 00:51:29   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:29     from module import app
2023-05-01 00:51:29   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:29     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:29   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:29     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:29   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:29     from .config import settings
2023-05-01 00:51:29   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:29     settings = env_to_config()
2023-05-01 00:51:29                ^^^^^^^^^^^^^^^
2023-05-01 00:51:29   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:29     return Setting(**_settings)
2023-05-01 00:51:29            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:29   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:29 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:29 rss_parser -> token
2023-05-01 00:51:29   none is not an allowed value (type=type_error.none.not_allowed)
2023-05-01 00:51:30 Traceback (most recent call last):
2023-05-01 00:51:30   File "/app/main.py", line 12, in <module>
2023-05-01 00:51:30     from module import app
2023-05-01 00:51:30   File "/app/module/app.py", line 5, in <module>
2023-05-01 00:51:30     from module.conf import settings, setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-01 00:51:30   File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-01 00:51:30     from .log import setup_logger, LOG_PATH
2023-05-01 00:51:30   File "/app/module/conf/log.py", line 3, in <module>
2023-05-01 00:51:30     from .config import settings
2023-05-01 00:51:30   File "/app/module/conf/config.py", line 73, in <module>
2023-05-01 00:51:30     settings = env_to_config()
2023-05-01 00:51:30                ^^^^^^^^^^^^^^^
2023-05-01 00:51:30   File "/app/module/conf/config.py", line 57, in env_to_config
2023-05-01 00:51:30     return Setting(**_settings)
2023-05-01 00:51:30            ^^^^^^^^^^^^^^^^^^^^
2023-05-01 00:51:30   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-05-01 00:51:30 pydantic.error_wrappers.ValidationError: 1 validation error for Setting
2023-05-01 00:51:30 rss_parser -> token
2023-05-01 00:51:30   none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by EstrellaXD** [comment]
请查看更新指南
