### ISSUE TITLE
[Discussion]: 我在创建容器时报错，是否是因为文件路径不对导致的，日志如下

### ISSUE THREAD

**Issue by wudingmao** [EstrellaXD/Auto_Bangumi#230]
### 项目讨论

2023-05-03 18:07:23.513757+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-03 18:07:23.513772+00:00File "/app/module/conf/config.py", line 33, in load_config_from_file
2023-05-03 18:07:23.513785+00:00config = json.load(f)
2023-05-03 18:07:23.513796+00:00^^^^^^^^^^^^
2023-05-03 18:07:23.513808+00:00File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
2023-05-03 18:07:23.513964+00:00return loads(fp.read(),
2023-05-03 18:07:23.514015+00:00^^^^^^^^^^^^^^^^
2023-05-03 18:07:23.514030+00:00File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
2023-05-03 18:07:23.514127+00:00return _default_decoder.decode(s)
2023-05-03 18:07:23.514167+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-03 18:07:23.514181+00:00File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
2023-05-03 18:07:23.514259+00:00obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023-05-03 18:07:23.514299+00:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-03 18:07:23.514313+00:00File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
2023-05-03 18:07:23.514373+00:00raise JSONDecodeError("Expecting value", s, err.value) from None
2023-05-03 18:07:23.514413+00:00json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-05-03 18:07:24.519327+00:00Traceback (most recent call last):
2023-05-03 18:07:24.519424+00:00File "/app/main.py", line 12, in <module>
2023-05-03 18:07:24.519449+00:00from module import app
2023-05-03 18:07:24.519466+00:00File "/app/module/app.py", line 5, in <module>
2023-05-03 18:07:24.519493+00:00from module.conf import setup_logger, LOG_PATH, DATA_PATH, RSSLink, VERSION
2023-05-03 18:07:24.519512+00:00File "/app/module/conf/__init__.py", line 1, in <module>
2023-05-03 18:07:24.519579+00:00from .log import setup_logger, LOG_PATH
2023-05-03 18:07:24.519607+00:00File "/app/module/conf/log.py", line 3, in <module>
2023-05-03 18:07:24.519637+00:00from .config import settings
2023-05-03 18:07:24.519653+00:00File "/app/module/conf/config.py", line 71, in <module>
2023-05-03 18:07:24.519667+00:00settings = load_config_from_file(CONFIG_PATH)

**Comment by wudingmao** [comment]
问题解决了，是/app/config下有之前的文件导致的
