### ISSUE TITLE
[错误报告]

### ISSUE THREAD

**Issue by masterspark2** [EstrellaXD/Auto_Bangumi#251]
### 当前程序版本

2.6.9

### 问题类型

程序运行问题

### 问题描述

auto_bangumi 启动后，在显示Finished后报错，显示IndexError: tuple index out of range，可以进入webui，运行状态为红色，重命名功能失效，下载功能依然有效。

### 发生问题时系统日志

```shell
�2023-05-11T01:41:56.478964181Z [2023-05-11 09:41:56,477] INFO:     Version 2.6.9  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
      w2023-05-11T01:41:56.480190685Z [2023-05-11 09:41:56,478] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
      [2023-05-11T01:41:56.481215348Z [2023-05-11 09:41:56,480] INFO:     Starting AutoBangumi...
      r2023-05-11T01:41:56.961317302Z [2023-05-11 09:41:56,959] WARNING:  Cannot add new category, maybe already exists.
      N2023-05-11T01:41:56.985009386Z [2023-05-11 09:41:56,982] INFO:     RSS Exist.
      T2023-05-11T01:41:57.033136749Z [2023-05-11 09:41:57,030] INFO:     Data file loaded
      ^2023-05-11T01:41:57.035547171Z [2023-05-11 09:41:57,033] INFO:     Start collecting RSS info.
      L2023-05-11T01:42:00.574979415Z [2023-05-11 09:42:00,571] INFO:     Finished
      O2023-05-11T01:42:00.576815233Z [2023-05-11 09:42:00,574] INFO:     Running....
      22023-05-11T01:42:02.166605494Z Process Process-1:
      B2023-05-11T01:42:02.187010665Z Traceback (most recent call last):
      v2023-05-11T01:42:02.187263549Z   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
      .2023-05-11T01:42:02.187341719Z     self.run()
      o2023-05-11T01:42:02.187367970Z   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
      M2023-05-11T01:42:02.187419013Z     self._target(*self._args, **self._kwargs)
      L2023-05-11T01:42:02.187443806Z   File "/app/module/app.py", line 82, in run
      Y2023-05-11T01:42:02.187489308Z     main_process(bangumi_data, download_client, settings)
      U2023-05-11T01:42:02.187514975Z   File "/app/module/app.py", line 53, in main_process
      32023-05-11T01:42:02.187538893Z     rename.rename()
      \2023-05-11T01:42:02.187585561Z   File "/app/module/manager/renamer.py", line 165, in rename
      n2023-05-11T01:42:02.187610645Z     bangumi_name, season = self.get_season_info(info.save_path, download_path)
      n2023-05-11T01:42:02.187763193Z                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      e2023-05-11T01:42:02.187793235Z   File "/app/module/manager/renamer.py", line 134, in get_season_info
      �2023-05-11T01:42:02.187818028Z     folder_name = path_parts[1] if path_parts[0] == "/" or path_parts[0] == "\\" else path_parts[0]
      P2023-05-11T01:42:02.187867905Z                                    ~~~~~~~~~~^^^
      D2023-05-11T01:42:02.187891822Z IndexError: tuple index out of range
```

**Comment by EstrellaXD** [comment]
download_path 配置有问题，请参考 Wiki 和 [#226 ](https://github.com/EstrellaXD/Auto_Bangumi/issues/242)https://github.com/EstrellaXD/Auto_Bangumi/issues/228

**Comment by masterspark2** [comment]
添加了/后已修复
