### ISSUE TITLE
[错误报告] qbittorrentapi.exceptions.Conflict409Error: 不正确的分类名

### ISSUE THREAD

**Issue by hahaVVV402** [EstrellaXD/Auto_Bangumi#300]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://github.com/EstrellaXD/Auto_Bangumi/wiki/排错流程)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://github.com/EstrellaXD/Auto_Bangumi/wiki/常见问题)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0.3

### 问题类型

程序运行问题

### 问题描述

qbittorrentapi.exceptions.Conflict409Error: 不正确的分类名
日志一直报错上述错误

### 发生问题时系统日志

```bash
[2023-06-05 17:33:58] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2023-06-05 17:33:58] INFO:     Starting AutoBangumi...
[2023-06-05 17:33:58] INFO:     Config loaded
[2023-06-05 17:33:59] INFO:     Program running.
[2023-06-05 17:33:59] INFO:     Application startup complete.
[2023-06-05 17:33:59] INFO:     Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
[2023-06-05 17:33:59] INFO:     [Renamer] Start rename collection
Exception in thread Thread-3 (rename_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 63, in rename_loop
    renamed_info = renamer.rename()
                   ^^^^^^^^^^^^^^^^
  File "/app/module/manager/renamer.py", line 172, in rename
    self.set_category(info.hash, "BangumiCollection")
  File "/app/module/downloader/download_client.py", line 147, in set_category
    self.client.set_category(hashes, category)
  File "/app/module/downloader/client/qb_downloader.py", line 135, in set_category
    self._client.torrents_set_category(category, hashes=_hash)
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 117, in wrapper
    return func(client, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 91, in wrapper
    return func(client, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 2128, in torrents_set_category
    self._post(_name=APINames.Torrents, _method="setCategory", data=data, **kwargs)
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 390, in _post
    return self._request_manager(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 465, in _request_manager
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 542, in _request
    self._handle_error_responses(data, params, response)
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 782, in _handle_error_responses
    raise Conflict409Error(response.text)
qbittorrentapi.exceptions.Conflict409Error: 不正确的分类名
[2023-06-05 17:34:09] WARNING:  [Network] Cannot connect to https://mikanime.tv/RSS/MyBangumi?token=K8ODQkR52bAkM%2bm8a5CCEA%3d%3d. Wait for 5 seconds.
[2023-06-05 17:34:24] WARNING:  [Network] Cannot connect to https://mikanime.tv/RSS/MyBangumi?token=K8ODQkR52bAkM%2bm8a5CCEA%3d%3d. Wait for 5 seconds.
[2023-06-05 17:34:39] WARNING:  [Network] Cannot connect to https://mikanime.tv/RSS/MyBangumi?token=K8ODQkR52bAkM%2bm8a5CCEA%3d%3d. Wait for 5 seconds.
[2023-06-05 17:34:39] ERROR     [Network] Failed connecting to https://mikanime.tv/RSS/MyBangumi?token=K8ODQkR52bAkM%2bm8a5CCEA%3d%3d
[2023-06-05 17:34:39] WARNING:  [Network] Please check DNS/Connection settings
```

**Comment by EstrellaXD** [comment]
是在重命名合集吗，如果你初始化跳过了，去 QB 里面新建 BangumiCollection 的分类名称即可解决
