### ISSUE TITLE
[错误报告] 只要打开parper setting的开关，就会提示重启失败，重启开始报错

### ISSUE THREAD

**Issue by 451725563** [EstrellaXD/Auto_Bangumi#351]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://github.com/EstrellaXD/Auto_Bangumi/wiki/排错流程)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://github.com/EstrellaXD/Auto_Bangumi/wiki/常见问题)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0.8; 3.0.7

### 问题类型

程序运行问题

### 问题描述

只要打开parper setting的开关，就会提示重启失败，重启容器后报错。
关掉开关后恢复正常，且手动添加下载的视频重命名也正常。
尝试退回3.0.7，问题也没有解决，在升级到3.0.8之前更新了python，不确定是不是这个原因

### 发生问题时系统日志

```bash
2023-06-20 23:20:54 [2023-06-20 23:20:54] INFO:     Version 3.0.8  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
2023-06-20 23:20:54 [2023-06-20 23:20:54] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
2023-06-20 23:20:54 [2023-06-20 23:20:54] INFO:     Starting AutoBangumi...
2023-06-20 23:20:54 [2023-06-20 23:20:54] INFO:     Config loaded
2023-06-20 23:20:56 [2023-06-20 23:20:56] ERROR     Traceback (most recent call last):
2023-06-20 23:20:56   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
2023-06-20 23:20:56     async with self.lifespan_context(app) as maybe_state:
2023-06-20 23:20:56   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
2023-06-20 23:20:56     await self._router.startup()
2023-06-20 23:20:56   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
2023-06-20 23:20:56     await handler()
2023-06-20 23:20:56   File "/app/module/api/program.py", line 18, in startup
2023-06-20 23:20:56     program.startup()
2023-06-20 23:20:56   File "/app/module/core/program.py", line 34, in startup
2023-06-20 23:20:56     self.start()
2023-06-20 23:20:56   File "/app/module/core/program.py", line 45, in start
2023-06-20 23:20:56     add_rss_feed()
2023-06-20 23:20:56   File "/app/module/core/rss_feed.py", line 16, in add_rss_feed
2023-06-20 23:20:56     if value.url == settings.rss_link:
2023-06-20 23:20:56        ^^^^^^^^^
2023-06-20 23:20:56   File "/usr/lib/python3.11/site-packages/qbittorrentapi/_attrdict.py", line 147, in __getattr__
2023-06-20 23:20:56     raise AttributeError(
2023-06-20 23:20:56 AttributeError: 'AttrDict' instance has no attribute 'url'
2023-06-20 23:20:56 
2023-06-20 23:20:56 [2023-06-20 23:20:56] ERROR     Application startup failed. Exiting.
```

**Comment by EstrellaXD** [comment]
QB 版本过低，升级可以解决
