### ISSUE TITLE
[错误报告]部署好后运行main.py错误:

### ISSUE THREAD

**Issue by UkokuGemini** [EstrellaXD/Auto_Bangumi#367]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://github.com/EstrellaXD/Auto_Bangumi/wiki/排错流程)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://github.com/EstrellaXD/Auto_Bangumi/wiki/常见问题)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0

### 问题类型

其他问题

### 问题描述

部署好后运行main.py错误:

### 发生问题时系统日志

```bash
D:\IdleSoft\Auto_Bangumi\backend\src>python main.py
Traceback (most recent call last):
  File "pydantic\main.py", line 522, in pydantic.main.BaseModel.parse_obj
ValueError: dictionary update sequence element #0 has length 1; 2 is required

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\IdleSoft\Auto_Bangumi\backend\src\main.py", line 4, in <module>
    from module.api import router
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\api\__init__.py", line 1, in <module>
    from .web import router
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\api\web.py", line 6, in <module>
    from .proxy import router
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\api\proxy.py", line 7, in <module>
    from .download import router
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\api\download.py", line 3, in <module>
    from .config import router
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\api\config.py", line 5, in <module>
    from .bangumi import router
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\api\bangumi.py", line 6, in <module>
    from .log import router
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\api\log.py", line 4, in <module>
    from .auth import router
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\api\auth.py", line 6, in <module>
    from module.security import (
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\security\__init__.py", line 2, in <module>
    from .api import get_current_user, get_token_data, auth_user, update_user_info
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\security\api.py", line 7, in <module>
    from module.database.user import AuthDB
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\database\__init__.py", line 1, in <module>
    from .bangumi import BangumiDatabase
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\database\bangumi.py", line 3, in <module>
    from module.database.connector import DataConnector
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\database\connector.py", line 6, in <module>
    from module.conf import DATA_PATH
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\conf\__init__.py", line 1, in <module>
    from .log import setup_logger, LOG_PATH
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\conf\log.py", line 4, in <module>
    from .config import settings
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\conf\config.py", line 87, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\conf\config.py", line 29, in __init__
    self.load()
  File "D:\IdleSoft\Auto_Bangumi\backend\src\module\conf\config.py", line 37, in load
    config_obj = Config.parse_obj(config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 525, in pydantic.main.BaseModel.parse_obj
pydantic.error_wrappers.ValidationError: 1 validation error for Config
__root__
  Config expected dict not str (type=type_error)
```

**Comment by zthxxx** [comment]
配置文件格式可能有问题，请把配置文件 config.json 发出来看看 （有token可以先删掉

**Comment by UkokuGemini** [comment]
> 配置文件格式可能有问题，请把配置文件 config.json 发出来看看 （有token可以先删掉

抱歉可能我的表述造成了理解上的偏差。
我按照[Windows 本地部署](https://github.com/EstrellaXD/Auto_Bangumi/wiki/Windows-%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2)执行顺利无报错直到最后一步Python Main.py开始报如上所述错误。
而非已经可以正常运行后报错。
本质上属于没部署成功，无法运行的问题。
由于注意到[配置选项说明](https://github.com/EstrellaXD/Auto_Bangumi/wiki/%E9%85%8D%E7%BD%AE%E9%80%89%E9%A1%B9%E8%AF%B4%E6%98%8E)

> 从 2.6 版本之后，AutoBangumi 使用 config.json 来配置系统设置。 初次运行 AutoBangumi 时会自动生成 config.json 文件，如果需要修改配置，可以直接修改 config.json 文件，也可以在 Web 界面中修改。

我想应该是没有生成config.json文件的。

**Comment by EstrellaXD** [comment]
> > 配置文件格式可能有问题，请把配置文件 config.json 发出来看看 （有token可以先删掉
> 
> 抱歉可能我的表述造成了理解上的偏差。 我按照[Windows 本地部署](https://github.com/EstrellaXD/Auto_Bangumi/wiki/Windows-%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2)执行顺利无报错直到最后一步Python Main.py开始报如上所述错误。 而非已经可以正常运行后报错。 本质上属于没部署成功，无法运行的问题。 由于注意到[配置选项说明](https://github.com/EstrellaXD/Auto_Bangumi/wiki/%E9%85%8D%E7%BD%AE%E9%80%89%E9%A1%B9%E8%AF%B4%E6%98%8E)
> 
> > 从 2.6 版本之后，AutoBangumi 使用 config.json 来配置系统设置。 初次运行 AutoBangumi 时会自动生成 config.json 文件，如果需要修改配置，可以直接修改 config.json 文件，也可以在 Web 界面中修改。
> 
> 我想应该是没有生成config.json文件的。

文档没有更新，尝试在 `backend\src` 目录下新建一个 `config` 文件夹

**Comment by UkokuGemini** [comment]
> > > 配置文件格式可能有问题，请把配置文件 config.json 发出来看看 （有token可以先删掉
> > 
> > 
> > 抱歉可能我的表述造成了理解上的偏差。 我按照[Windows 本地部署](https://github.com/EstrellaXD/Auto_Bangumi/wiki/Windows-%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2)执行顺利无报错直到最后一步Python Main.py开始报如上所述错误。 而非已经可以正常运行后报错。 本质上属于没部署成功，无法运行的问题。 由于注意到[配置选项说明](https://github.com/EstrellaXD/Auto_Bangumi/wiki/%E9%85%8D%E7%BD%AE%E9%80%89%E9%A1%B9%E8%AF%B4%E6%98%8E)
> > > 从 2.6 版本之后，AutoBangumi 使用 config.json 来配置系统设置。 初次运行 AutoBangumi 时会自动生成 config.json 文件，如果需要修改配置，可以直接修改 config.json 文件，也可以在 Web 界面中修改。
> > 
> > 
> > 我想应该是没有生成config.json文件的。
> 
> 文档没有更新，尝试在 `backend\src` 目录下新建一个 `config` 文件夹

按照步骤6已经建立该文件夹了。
`mkdir src\config`
`echo "{}" > src\config\config_dev.json`

**Comment by EstrellaXD** [comment]
> > > > 配置文件格式可能有问题，请把配置文件 config.json 发出来看看 （有token可以先删掉
> > > 
> > > 
> > > 抱歉可能我的表述造成了理解上的偏差。 我按照[Windows 本地部署](https://github.com/EstrellaXD/Auto_Bangumi/wiki/Windows-%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2)执行顺利无报错直到最后一步Python Main.py开始报如上所述错误。 而非已经可以正常运行后报错。 本质上属于没部署成功，无法运行的问题。 由于注意到[配置选项说明](https://github.com/EstrellaXD/Auto_Bangumi/wiki/%E9%85%8D%E7%BD%AE%E9%80%89%E9%A1%B9%E8%AF%B4%E6%98%8E)
> > > > 从 2.6 版本之后，AutoBangumi 使用 config.json 来配置系统设置。 初次运行 AutoBangumi 时会自动生成 config.json 文件，如果需要修改配置，可以直接修改 config.json 文件，也可以在 Web 界面中修改。
> > > 
> > > 
> > > 我想应该是没有生成config.json文件的。
> > 
> > 
> > 文档没有更新，尝试在 `backend\src` 目录下新建一个 `config` 文件夹
> 
> 按照步骤6已经建立该文件夹了。 `mkdir src\config` `echo "{}" > src\config\config_dev.json`

因为后续改了一部分文件目录，现在应该在 `backend\src` 下创建

**Comment by UkokuGemini** [comment]
> > > > > 配置文件格式可能有问题，请把配置文件 config.json 发出来看看 （有token可以先删掉
> > > > 
> > > > 
> > > > 抱歉可能我的表述造成了理解上的偏差。 我按照[Windows 本地部署](https://github.com/EstrellaXD/Auto_Bangumi/wiki/Windows-%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2)执行顺利无报错直到最后一步Python Main.py开始报如上所述错误。 而非已经可以正常运行后报错。 本质上属于没部署成功，无法运行的问题。 由于注意到[配置选项说明](https://github.com/EstrellaXD/Auto_Bangumi/wiki/%E9%85%8D%E7%BD%AE%E9%80%89%E9%A1%B9%E8%AF%B4%E6%98%8E)
> > > > > 从 2.6 版本之后，AutoBangumi 使用 config.json 来配置系统设置。 初次运行 AutoBangumi 时会自动生成 config.json 文件，如果需要修改配置，可以直接修改 config.json 文件，也可以在 Web 界面中修改。
> > > > 
> > > > 
> > > > 我想应该是没有生成config.json文件的。
> > > 
> > > 
> > > 文档没有更新，尝试在 `backend\src` 目录下新建一个 `config` 文件夹
> > 
> > 
> > 按照步骤6已经建立该文件夹了。 `mkdir src\config` `echo "{}" > src\config\config_dev.json`
> 
> 因为后续改了一部分文件目录，现在应该在 `backend\src` 下创建


问题解决：做法是不执行`echo "{}" > src\config\config_dev.json`
或者删除该文件。
