### ISSUE TITLE
用反代后的订阅首页不显示订阅的番剧

### ISSUE THREAD

**Issue by spirytuslove** [EstrellaXD/Auto_Bangumi#455]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1-beta.5

### 问题类型

程序运行问题

### 问题描述

3.1-beta.5用反代后的订阅首页不显示订阅的番剧 当正式版3.0.12却可以正常订阅显示 查看测试版日志也没有报错
<img width="754" alt="iShot_2023-09-21_21 24 07" src="https://github.com/EstrellaXD/Auto_Bangumi/assets/64483414/d15a7258-87d2-4d06-bbbb-8b386ad1a5af">

**Comment by EstrellaXD** [comment]
是否可以开一下 Debug 重启容器再看一下，我这边没办法复现。

**Comment by spirytuslove** [comment]
日志显示这个[2023-09-22 08:27:09] DEBUG:    Using selector: EpollSelector
[2023-09-22 08:27:09] INFO:     Started server process [7]
[2023-09-22 08:27:09] INFO:     Waiting for application startup.
[2023-09-22 08:27:09] INFO:     
[2023-09-22 08:27:09] INFO:                     _        ____                                    _
[2023-09-22 08:27:09] INFO:          /\        | |      |  _ \                                  (_)
[2023-09-22 08:27:09] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _
[2023-09-22 08:27:09] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2023-09-22 08:27:09] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2023-09-22 08:27:09] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2023-09-22 08:27:09] INFO:                                                 __/ |
[2023-09-22 08:27:09] INFO:                                                |___/
[2023-09-22 08:27:09] INFO:     Version 3.1-beta.5  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2023-09-22 08:27:09] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2023-09-22 08:27:09] INFO:     Starting AutoBangumi...
[2023-09-22 08:27:09] INFO:     Config loaded
[2023-09-22 08:27:09] DEBUG:    Starting new HTTP connection (1): 10.10.10.10:8080
[2023-09-22 08:27:09] DEBUG:    http://10.10.10.10:8080 "GET / HTTP/1.1" 200 639
[2023-09-22 08:27:09] DEBUG:    Re-initializing context...
[2023-09-22 08:27:09] DEBUG:    [Downloader] Authed.
[2023-09-22 08:27:09] INFO:     Program running.
[2023-09-22 08:27:09] INFO:     Application startup complete.
[2023-09-22 08:27:09] INFO:     Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
[2023-09-22 08:27:09] DEBUG:    [Downloader] Authed.
[2023-09-22 08:27:09] DEBUG:    [Renamer] Start rename process.
[2023-09-22 08:27:09] DEBUG:    [Downloader] Authed.
[2023-09-22 08:27:09] DEBUG:    [Renamer] Rename process finished.
[2023-09-22 08:27:10] DEBUG:    RAW:[ANi] Jujutsu Kaisen S02 -  咒术回战 第二季 - 33 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4] >> Jujutsu Kaisen
[2023-09-22 08:27:19] DEBUG:    Calling on_field_start with no data
[2023-09-22 08:27:19] DEBUG:    Calling on_field_name with data[0:8]
[2023-09-22 08:27:19] DEBUG:    Calling on_field_data with data[9:14]
[2023-09-22 08:27:19] DEBUG:    Calling on_field_end with no data
[2023-09-22 08:27:19] DEBUG:    Calling on_field_start with no data
[2023-09-22 08:27:19] DEBUG:    Calling on_field_name with data[15:23]
[2023-09-22 08:27:19] DEBUG:    Calling on_field_data with data[24:34]
[2023-09-22 08:27:19] DEBUG:    Calling on_field_end with no data
[2023-09-22 08:27:19] DEBUG:    Calling on_end with no data
[2023-09-22 08:27:19] DEBUG:    detected 'bcrypt' backend, version '4.0.1'
[2023-09-22 08:27:19] DEBUG:    'bcrypt' backend lacks $2$ support, enabling workaround
[2023-09-22 08:28:10] DEBUG:    [Downloader] Authed.
[2023-09-22 08:28:10] DEBUG:    [Renamer] Start rename process.
[2023-09-22 08:28:10] DEBUG:    [Renamer] Rename process finished.
[2023-09-22 08:28:21] INFO:     Config loaded
[2023-09-22 08:28:21] INFO:     Program running.
[2023-09-22 08:28:22] DEBUG:    [Downloader] Authed.
[2023-09-22 08:28:22] DEBUG:    [Renamer] Start rename process.
[2023-09-22 08:28:22] DEBUG:    [Downloader] Authed.
[2023-09-22 08:28:22] DEBUG:    [Renamer] Rename process finished.
[2023-09-22 08:28:22] DEBUG:    RAW:[ANi] Jujutsu Kaisen S02 -  咒术回战 第二季 - 33 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4] >> Jujutsu Kaisen

**Comment by spirytuslove** [comment]
同样的订阅在3.0.2可以正常显示

**Comment by EstrellaXD** [comment]
大版本升级有一个数据库升级的过程，如果切换的话可能会造成这样的结果，建议你新建一个容器绑定新目录再试试

**Comment by spirytuslove** [comment]
> 大版本升级有一个数据库升级的过程，如果切换的话可能会造成这样的结果，建议你新建一个容器绑定新目录再试试

我直接把ab测试版删了重新新建容器 配置绑定在新建的卷里面好像也还是同样情况 日志没问题但就是首页就是加载不出来 换回原来的正式版本首页就能加载 一切正常 这是我的命令
docker run -d --name=AutoBangumi -v autobangumi:/app/config -v autobangumi:/app/data -p 7892:7892 --network=bridge --dns=8.8.8.8 --restart unless-stopped estrellaxd/auto_bangumi:dev-latest

**Comment by EstrellaXD** [comment]
> -v autobangumi:/app/config -v autobangumi:/app/data 
你的两个容器公用了一个 Volume？

> 建议你新建一个容器绑定新目录再试试

**Comment by spirytuslove** [comment]
用的是不是同一个volume 我是重新新建的卷 [data.db.zip](https://github.com/EstrellaXD/Auto_Bangumi/files/12700811/data.db.zip)

**Comment by spirytuslove** [comment]
用的是不同的volume 我是重新新建了一个卷  命名不同 
[data.db.zip](https://github.com/EstrellaXD/Auto_Bangumi/files/12700821/data.db.zip)

**Comment by spirytuslove** [comment]
我看了下测试版容器日志里面有这个错误
TypeError: cannot unpack non-iterable NoneType object
[2023-09-22 21:10:04] INFO:     Config loaded
[2023-09-22 21:10:04] INFO:     Config updated
[2023-09-22 21:10:04] INFO:     Config loaded
[2023-09-22 21:10:04] INFO:     Program running.
Exception in thread Thread-6 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 27, in rss_loop
    self.analyser.rss_to_data(rss, engine)
  File "/app/module/rss/analyser.py", line 75, in rss_to_data
    new_data = self.torrents_to_data(torrents_to_add, rss, full_parse)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/rss/analyser.py", line 52, in torrents_to_data
    self.official_title_parser(bangumi=bangumi, rss=rss, torrent=torrent)
  File "/app/module/rss/analyser.py", line 25, in official_title_parser
    tmdb_title, season, year, poster_link = self.tmdb_parser(
                                            ^^^^^^^^^^^^^^^^^
  File "/app/module/parser/title_parser.py", line 29, in tmdb_parser
    tmdb_info = tmdb_parser(title, language)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/parser/analyser/tmdb_parser.py", line 78, in tmdb_parser
    last_season, poster_path = get_season(season)
    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
但是正式版后台没这个错误日志显示 并且订阅都正常

**Comment by EstrellaXD** [comment]
收到，大概定位到错误了，感谢

**Comment by spirytuslove** [comment]
> 收到，大概定位到错误了，感谢

辛苦修复 终于可以用新版本了😂

**Comment by spirytuslove** [comment]
> 收到，大概定位到错误了，感谢
测试版6现在首页可以加载的 但我订阅的死神首页识别成了死神少爷与黑女仆
 后台日志
[2023-09-24 07:52:28] INFO:     Config loaded
[2023-09-24 07:52:28] INFO:     Program running.
[2023-09-24 07:52:29] INFO:     [RSS] New bangumi founded: 死神少爷与黑女仆
[2023-09-24 07:52:30] INFO:     Start collecting full season...
[2023-09-24 07:52:30] INFO:     Start collecting 死神少爷与黑女仆 Season 1...
Exception in thread Thread-14 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 31, in rss_loop
    eps_complete()
  File "/app/module/manager/collector.py", line 61, in eps_complete
    sc.collect_season(data)
  File "/app/module/manager/collector.py", line 21, in collect_season
    if self.add_torrent(torrents, bangumi):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/downloader/download_client.py", line 122, in add_torrent
    if "magnet" in torrent[0].url:
                   ~~~~~~~^^^

**Comment by EstrellaXD** [comment]
@spirytuslove 这个日志报错的错误部分还有么，应该还有几段

**Comment by spirytuslove** [comment]
> @spirytuslove 这个日志报错的错误部分还有么，应该还有几段

[2023-09-24 07:49:57] INFO:     Start collecting full season...
[2023-09-24 07:49:57] INFO:     Start collecting 死神 Season 2...
Exception in thread Thread-8 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 31, in rss_loop
    eps_complete()
  File "/app/module/manager/collector.py", line 61, in eps_complete
    sc.collect_season(data)
  File "/app/module/manager/collector.py", line 21, in collect_season
    if self.add_torrent(torrents, bangumi):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/downloader/download_client.py", line 122, in add_torrent
    if "magnet" in torrent[0].url:
                   ~~~~~~~^^^
IndexError: list index out of range
[2023-09-24 07:50:10] INFO:     [Manager] Delete rule for 死神少爷与黑女仆
[2023-09-24 07:50:30] INFO:     [Manager] Delete rule for 死神
[2023-09-24 07:50:51] INFO:     Config loaded
[2023-09-24 07:50:51] INFO:     Config updated
[2023-09-24 07:50:51] INFO:     Config loaded
[2023-09-24 07:50:51] INFO:     Program running.
[2023-09-24 07:50:52] INFO:     [RSS] New bangumi founded: 死神少爷与黑女仆
[2023-09-24 07:50:53] INFO:     Start collecting full season...
[2023-09-24 07:50:54] INFO:     Start collecting 咒术回战 Season 1...
[2023-09-24 07:50:55] WARNING:  Collection of 咒术回战 Season 1 failed.
[2023-09-24 07:50:55] INFO:     Start collecting 僵尸百分百～变成僵尸之前想做的100件事～ Season 1...
[2023-09-24 07:50:57] WARNING:  Collection of 僵尸百分百～变成僵尸之前想做的100件事～ Season 1 failed.
[2023-09-24 07:50:57] INFO:     Start collecting 死神少爷与黑女仆 Season 1...
Exception in thread Thread-10 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 31, in rss_loop
    eps_complete()
  File "/app/module/manager/collector.py", line 61, in eps_complete
    sc.collect_season(data)
  File "/app/module/manager/collector.py", line 21, in collect_season
    if self.add_torrent(torrents, bangumi):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/downloader/download_client.py", line 122, in add_torrent
    if "magnet" in torrent[0].url:
                   ~~~~~~~^^^
IndexError: list index out of range
[2023-09-24 07:52:19] INFO:     Config loaded
[2023-09-24 07:52:19] INFO:     Program running.
[2023-09-24 07:52:21] INFO:     [RSS] New bangumi founded: 死神少爷与黑女仆
[2023-09-24 07:52:21] INFO:     [RSS] New bangumi founded: 咒术回战
[2023-09-24 07:52:22] INFO:     [RSS] New bangumi founded: 无职转生 ～到了异世界就拿出真本事～
[2023-09-24 07:52:22] INFO:     [RSS] New bangumi founded: 僵尸百分百～变成僵尸之前想做的100件事～
[2023-09-24 07:52:23] INFO:     Start collecting full season...
[2023-09-24 07:52:23] INFO:     Start collecting 死神少爷与黑女仆 Season 1...
Exception in thread Thread-12 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 31, in rss_loop
    eps_complete()
  File "/app/module/manager/collector.py", line 61, in eps_complete
    sc.collect_season(data)
  File "/app/module/manager/collector.py", line 21, in collect_season
    if self.add_torrent(torrents, bangumi):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/downloader/download_client.py", line 122, in add_torrent
    if "magnet" in torrent[0].url:
                   ~~~~~~~^^^
IndexError: list index out of range
[2023-09-24 07:52:28] INFO:     Config loaded
[2023-09-24 07:52:28] INFO:     Program running.
[2023-09-24 07:52:29] INFO:     [RSS] New bangumi founded: 死神少爷与黑女仆
[2023-09-24 07:52:30] INFO:     Start collecting full season...
[2023-09-24 07:52:30] INFO:     Start collecting 死神少爷与黑女仆 Season 1...
Exception in thread Thread-14 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 31, in rss_loop
    eps_complete()
  File "/app/module/manager/collector.py", line 61, in eps_complete
    sc.collect_season(data)
  File "/app/module/manager/collector.py", line 21, in collect_season
    if self.add_torrent(torrents, bangumi):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/downloader/download_client.py", line 122, in add_torrent
    if "magnet" in torrent[0].url:
                   ~~~~~~~^^^
IndexError: list index out of range
[2023-09-24 07:55:25] INFO:     Shutting down
[2023-09-24 07:55:25] INFO:     Waiting for application shutdown.
[2023-09-24 07:55:25] INFO:     Application shutdown complete.
[2023-09-24 07:55:25] INFO:     Finished server process [7]

**Comment by EstrellaXD** [comment]
收到，识别问题可以去单独的 ISSUE 模板提一个新 ISSUE
