### ISSUE TITLE
[错误报告] 启动失败 ValueError: 3.1-beta.4 is not valid SemVer string

### ISSUE THREAD

**Issue by Ovler-Young** [EstrellaXD/Auto_Bangumi#487]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.0-beta.6

### 问题类型

程序运行问题

### 问题描述

目前我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 中的dev中最新版相同。
dev-latest 这个tag的最后一个版本`3.1.0-beta.6`启动失败，报错：
```
ValueError: 3.1-beta.4 is not valid SemVer string
 ```

还有很奇怪的是当前程序版本为`3.1.0-beta.6`但报错信息为`3.1-beta.4`，令人摸不着头脑。

目前最新版本已经不是`3.1.0-beta.6`了，但这已经是dev-latest的最新，

### 发生问题时系统日志

```bash
[2023-09-29 01:02:16] INFO:     Started server process [7]
[2023-09-29 01:02:16] INFO:     Waiting for application startup.
[2023-09-29 01:02:16] INFO:     
[2023-09-29 01:02:16] INFO:                     _        ____                                    _
[2023-09-29 01:02:16] INFO:          /\        | |      |  _ \                                  (_)
[2023-09-29 01:02:16] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _
[2023-09-29 01:02:16] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2023-09-29 01:02:16] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2023-09-29 01:02:16] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2023-09-29 01:02:16] INFO:                                                 __/ |
[2023-09-29 01:02:16] INFO:                                                |___/
[2023-09-29 01:02:16] INFO:     Version 3.1.0-beta.6  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2023-09-29 01:02:16] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2023-09-29 01:02:16] INFO:     Starting AutoBangumi...
[2023-09-29 01:02:16] ERROR     Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/app/module/api/program.py", line 22, in startup
    program.startup()
  File "/app/module/core/program.py", line 45, in startup
    elif self.version_update:
         ^^^^^^^^^^^^^^^^^^^
  File "/app/module/core/status.py", line 52, in version_update
    return not self.check_version()
               ^^^^^^^^^^^^^^^^^^^^
  File "/app/module/checker/checker.py", line 40, in check_version
    return version_check()
           ^^^^^^^^^^^^^^^
  File "/app/module/update/version_check.py", line 18, in version_check
    last_ver = semver.VersionInfo.parse(last_version)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/semver/version.py", line 646, in parse
    raise ValueError(f"{version} is not valid SemVer string")
ValueError: 3.1-beta.4
 is not valid SemVer string
[2023-09-29 01:02:16] ERROR     Application startup failed. Exiting.
```

**Comment by Ovler-Young** [comment]
更新：将docker的tag更改为latest之后仍然报同样的错误。
```
usermod: no changes
[2023-09-29 01:18:35] INFO:     Started server process [8]
[2023-09-29 01:18:35] INFO:     Waiting for application startup.
[2023-09-29 01:18:35] INFO:     
[2023-09-29 01:18:35] INFO:                     _        ____                                    _
[2023-09-29 01:18:35] INFO:          /\        | |      |  _ \                                  (_)
[2023-09-29 01:18:35] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _
[2023-09-29 01:18:35] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2023-09-29 01:18:35] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2023-09-29 01:18:35] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2023-09-29 01:18:35] INFO:                                                 __/ |
[2023-09-29 01:18:35] INFO:                                                |___/
[2023-09-29 01:18:35] INFO:     Version 3.1.2  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2023-09-29 01:18:35] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2023-09-29 01:18:35] INFO:     Starting AutoBangumi...
[2023-09-29 01:18:35] ERROR     Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/app/module/api/program.py", line 22, in startup
    program.startup()
  File "/app/module/core/program.py", line 45, in startup
    elif self.version_update:
         ^^^^^^^^^^^^^^^^^^^
  File "/app/module/core/status.py", line 52, in version_update
    return not self.check_version()
               ^^^^^^^^^^^^^^^^^^^^
  File "/app/module/checker/checker.py", line 40, in check_version
    return version_check()
           ^^^^^^^^^^^^^^^
  File "/app/module/update/version_check.py", line 18, in version_check
    last_ver = semver.VersionInfo.parse(last_version)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/semver/version.py", line 646, in parse
    raise ValueError(f"{version} is not valid SemVer string")
ValueError: 3.1-beta.4
 is not valid SemVer string
[2023-09-29 01:18:35] ERROR     Application startup failed. Exiting.
```

**Comment by Ovler-Young** [comment]
更新：
怀疑是映射问题。
我docker中有如下映射配置：
```
Host/volume | Path in container
/data/compose/autoBangumiConf | /app/config
/data/compose/autoBangumi | /app/data
```
其中 `/data/compose/autoBangumiConf ` 目录下存在 `version.info` 文件，内容即为`3.1-beta.4`。
似乎由于已经将配置持久化了，`version.info`并不能自动的进行更新。手动将其内容更改为`3.1.2`后，能够正常启动。

**Comment by EstrellaXD** [comment]
这个问题是beta版本升级到正式版的问题，正常升级应该不会存在。
