### ISSUE TITLE
[错误报告]AB可以连接上mikan但无法解析rss

### ISSUE THREAD

**Issue by asgh215** [EstrellaXD/Auto_Bangumi#489]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.2

### 问题类型

程序运行问题

### 问题描述

通过AB的搜索栏得到的番剧可以正常订阅下载，但是从mikan获得的rss token无法解析，另外在订阅时的规则编辑里的番剧偏移是什么功能，尝试设置以后没有发现有作用。使用的环境为群晖7.1 docker部署，使用了旁路由openclash代理，部署过程中没有设置dns

### 发生问题时系统日志

```bash
[2023-09-30 18:31:28] WARNING:  [Network] Cannot connect to MAB9Jug%2bcbCfSrY5pf6Aag%3d%3d. Wait for 5 seconds.
[2023-09-30 18:31:33] WARNING:  [Network] Cannot connect to MAB9Jug%2bcbCfSrY5pf6Aag%3d%3d. Wait for 5 seconds.
[2023-09-30 18:31:38] WARNING:  [Network] Cannot connect to MAB9Jug%2bcbCfSrY5pf6Aag%3d%3d. Wait for 5 seconds.
[2023-09-30 18:31:38] ERROR     [Network] Failed connecting to MAB9Jug%2bcbCfSrY5pf6Aag%3d%3d
[2023-09-30 18:31:38] WARNING:  [Network] Please check DNS/Connection settings
[2023-09-30 18:31:38] WARNING:  [Network] Failed to get torrents: MAB9Jug%2bcbCfSrY5pf6Aag%3d%3d
[2023-09-30 18:31:38] ERROR     Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/api/rss.py", line 135, in analysis
    return u_response(data)
           ^^^^^^^^^^^^^^^^
  File "/app/module/api/response.py", line 9, in u_response
    status_code=response_model.status_code,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
[2023-09-30 18:40:46] INFO:     [LoliHouse] Nanatsu no Maken ga Shihai suru - 13 [WebRip 1080p HEVC-10bit AAC SRTx2].mkv >> Nanatsu no Maken ga Shihai suru S01E13.mkv
[2023-09-30 18:46:29] WARNING:  [Network] Cannot connect to MAB9Jug%2bcbCfSrY5pf6Aag%3d%3d. Wait for 5 seconds.
[2023-09-30 18:46:34] WARNING:  [Network] Cannot connect to MAB9Jug%2bcbCfSrY5pf6Aag%3d%3d. Wait for 5 seconds.
[2023-09-30 18:46:39] WARNING:  [Network] Cannot connect to MAB9Jug%2bcbCfSrY5pf6Aag%3d%3d. Wait for 5 seconds.
[2023-09-30 18:46:39] ERROR     [Network] Failed connecting to MAB9Jug%2bcbCfSrY5pf6Aag%3d%3d
[2023-09-30 18:46:39] WARNING:  [Network] Please check DNS/Connection settings
[2023-09-30 18:46:39] WARNING:  [Network] Failed to get torrents: MAB9Jug%2bcbCfSrY5pf6Aag%3d%3d
[2023-09-30 18:46:39] ERROR     Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/api/rss.py", line 135, in analysis
    return u_response(data)
           ^^^^^^^^^^^^^^^^
  File "/app/module/api/response.py", line 9, in u_response
    status_code=response_model.status_code,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
```

**Comment by EstrellaXD** [comment]
在报错的时候进行了什么操作。

**Comment by asgh215** [comment]
> 在报错的时候进行了什么操作。

在mikan project复制了rss链接中token=后面的内容，填入添加rss中的rss链接，其他设置保持默认添加

**Comment by EstrellaXD** [comment]
3.1 的添加方式修改了，直接复制 RSS 地址添加聚合 RSS 即可。
