### ISSUE TITLE
[错误报告]容器内部可访问到mikan，web无法访问

### ISSUE THREAD

**Issue by 991547436** [EstrellaXD/Auto_Bangumi#498]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.3

### 问题类型

WebUI

### 问题描述

如下图 容器内wget可以访问到mikan的rss，安装配置文件未设置dns，web未设置代理

![QQ截图20231003013608](https://github.com/EstrellaXD/Auto_Bangumi/assets/15355274/74bd0bad-d412-47bd-bd8d-78fdc14cc760)

![QQ截图20231003014223](https://github.com/EstrellaXD/Auto_Bangumi/assets/15355274/cba6857b-bb65-4388-9bb9-b82f352479a0)

docker-compose.yml 
version: "3.8"

services:
  autobangumi:
    image: estrellaxd/auto_bangumi:latest
    container_name: autobangumi
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /usr/local/AutoBangumi/config:/app/config
      - /usr/local/AutoBangumi/data:/app/data
    network_mode: bridge
    ports:
      - '7892:7892'

### 发生问题时系统日志

```bash
faviconAutoBangumi
输入关键字搜索
Log
[2023-10-03 01:37:50] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:37:55] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:38:00] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:38:00] ERROR     [Network] Failed connecting to mikan
[2023-10-03 01:38:00] WARNING:  [Network] Please check DNS/Connection settings
[2023-10-03 01:38:00] WARNING:  [Network] Failed to get torrents: mikan
[2023-10-03 01:38:00] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:38:05] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:38:10] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:38:10] ERROR     [Network] Failed connecting to mikan
[2023-10-03 01:38:10] WARNING:  [Network] Please check DNS/Connection settings
[2023-10-03 01:38:10] WARNING:  [Network] Failed to get torrents: mikan
[2023-10-03 01:38:47] WARNING:  [Network] Cannot connect to 12. Wait for 5 seconds.
[2023-10-03 01:38:52] WARNING:  [Network] Cannot connect to 12. Wait for 5 seconds.
[2023-10-03 01:38:57] WARNING:  [Network] Cannot connect to 12. Wait for 5 seconds.
[2023-10-03 01:38:57] ERROR     [Network] Failed connecting to 12
[2023-10-03 01:38:57] WARNING:  [Network] Please check DNS/Connection settings
[2023-10-03 01:38:57] WARNING:  [Network] Failed to get torrents: 12
[2023-10-03 01:38:57] ERROR     Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/api/rss.py", line 135, in analysis
    return u_response(data)
           ^^^^^^^^^^^^^^^^
  File "/app/module/api/response.py", line 9, in u_response
    status_code=response_model.status_code,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
[2023-10-03 01:39:10] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:39:15] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:39:20] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:39:20] ERROR     [Network] Failed connecting to mikan
[2023-10-03 01:39:20] WARNING:  [Network] Please check DNS/Connection settings
[2023-10-03 01:39:20] WARNING:  [Network] Failed to get torrents: mikan
[2023-10-03 01:39:20] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:39:25] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:39:30] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:39:30] ERROR     [Network] Failed connecting to mikan
[2023-10-03 01:39:30] WARNING:  [Network] Please check DNS/Connection settings
[2023-10-03 01:39:30] WARNING:  [Network] Failed to get torrents: mikan
[2023-10-03 01:40:30] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:40:35] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:40:40] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:40:40] ERROR     [Network] Failed connecting to mikan
[2023-10-03 01:40:40] WARNING:  [Network] Please check DNS/Connection settings
[2023-10-03 01:40:40] WARNING:  [Network] Failed to get torrents: mikan
[2023-10-03 01:40:40] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:40:45] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:40:50] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:40:50] ERROR     [Network] Failed connecting to mikan
[2023-10-03 01:40:50] WARNING:  [Network] Please check DNS/Connection settings
[2023-10-03 01:40:50] WARNING:  [Network] Failed to get torrents: mikan
[2023-10-03 01:41:50] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:41:55] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:42:00] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:42:00] ERROR     [Network] Failed connecting to mikan
[2023-10-03 01:42:00] WARNING:  [Network] Please check DNS/Connection settings
[2023-10-03 01:42:00] WARNING:  [Network] Failed to get torrents: mikan
[2023-10-03 01:42:00] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:42:05] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:42:10] WARNING:  [Network] Cannot connect to mikan. Wait for 5 seconds.
[2023-10-03 01:42:10] ERROR     [Network] Failed connecting to mikan
[2023-10-03 01:42:10] WARNING:  [Network] Please check DNS/Connection settings
[2023-10-03 01:42:10] WARNING:  [Network] Failed to get torrents: mikan

重置

复制
Github
访问
Official Website
访问
X
访问
Telegram Group
加入
Github Issue
Version: 3.1.3
```

**Comment by 991547436** [comment]
尴尬了 名称和url写反了，程序正常
顺带提一下，如果家里是路由器代理的使用MosDNS进行dns分流，docker compose配置文件的dns要删掉，否则容器通过指定dns无法访问网络

**Comment by 991547436** [comment]
尴尬了 名称和url写反了，程序正常
顺带提一下，如果家里是路由器代理的使用MosDNS进行dns分流，docker compose配置文件的dns要删掉，否则容器通过指定dns无法访问网络
