### ISSUE TITLE
[Discussion] 开启了代理设置SSR订阅依然无法连接

### ISSUE THREAD

**Issue by 1049480196** [EstrellaXD/Auto_Bangumi#530]
### 项目讨论

我在qBittorrent上订阅mikan的SSR地址设置代理后可以更新成功，但是相同的代理设置在AutoBangumi中设置后，同样的mikan的SSR连接却无法连接，我使用的是代理设置类型为Socks5
[2023-10-06 00:30:25] WARNING:  [Network] Cannot connect to http://mikanani.me/RSS/Bangumi?bangumiId=3056&subgroupid=552. Wait for 5 seconds.
[2023-10-06 00:30:35] WARNING:  [Network] Cannot connect to http://mikanani.me/RSS/Bangumi?bangumiId=3056&subgroupid=552. Wait for 5 seconds.
[2023-10-06 00:30:45] WARNING:  [Network] Cannot connect to http://mikanani.me/RSS/Bangumi?bangumiId=3056&subgroupid=552. Wait for 5 seconds.
[2023-10-06 00:30:45] ERROR     [Network] Failed connecting to http://mikanani.me/RSS/Bangumi?bangumiId=3056&subgroupid=552
[2023-10-06 00:30:45] WARNING:  [Network] Please check DNS/Connection settings
[2023-10-06 00:30:45] WARNING:  [Network] Failed to get torrents: http://mikanani.me/RSS/Bangumi?bangumiId=3056&subgroupid=552
[2023-10-06 00:30:45] ERROR     Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/api/rss.py", line 182, in analysis
    return u_response(data)
           ^^^^^^^^^^^^^^^^
  File "/app/module/api/response.py", line 9, in u_response
    status_code=response_model.status_code,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'

**Comment by 1049480196** [comment]
> ### 项目讨论
> 我在qBittorrent上订阅mikan的SSR地址设置代理后可以更新成功，但是相同的代理设置在AutoBangumi中设置后，同样的mikan的SSR连接却无法连接，我使用的是代理设置类型为Socks5
[2023-10-06 00:30:25] WARNING:  [Network] Cannot connect to http://mikanani.me/RSS/Bangumi?bangumiId=3056&subgroupid=552. Wait for 5 seconds.
[2023-10-06 00:30:35] WARNING:  [Network] Cannot connect to http://mikanani.me/RSS/Bangumi?bangumiId=3056&subgroupid=552. Wait for 5 seconds.
[2023-10-06 00:30:45] WARNING:  [Network] Cannot connect to http://mikanani.me/RSS/Bangumi?bangumiId=3056&subgroupid=552. Wait for 5 seconds.
[2023-10-06 00:30:45] ERROR     [Network] Failed connecting to http://mikanani.me/RSS/Bangumi?bangumiId=3056&subgroupid=552
[2023-10-06 00:30:45] WARNING:  [Network] Please check DNS/Connection settings
[2023-10-06 00:30:45] WARNING:  [Network] Failed to get torrents: http://mikanani.me/RSS/Bangumi?bangumiId=3056&subgroupid=552
[2023-10-06 00:30:45] ERROR     Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/api/rss.py", line 182, in analysis
    return u_response(data)
           ^^^^^^^^^^^^^^^^
  File "/app/module/api/response.py", line 9, in u_response
    status_code=response_model.status_code,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
