### ISSUE TITLE
[错误报告]不能订阅此RSS链接

### ISSUE THREAD

**Issue by xfrqh** [EstrellaXD/Auto_Bangumi#576]
### 确认

- [ ] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.9

### 问题类型

程序运行问题

### 问题描述

问题：不能订阅[这条RSS链接](https://mikanani.me/RSS/Bangumi?bangumiId=3177&subgroupid=615)

### 复现

<img width="270" alt="2023-10-14_14-44-20" src="https://github.com/EstrellaXD/Auto_Bangumi/assets/73733485/7f498f74-14bb-444e-bd92-675d2d3dc467">

点击订阅后就提示![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/73733485/6c4c2237-49a1-4e0e-a029-e06969fde5ba)

然后RSS管理中有此条目，但主页没有此番剧的海报

### 发生问题时系统日志

```bash
[2023-10-14 14:28:32] WARNING:  [Network] Cannot connect to https://mikanani.me/RSS/Bangumi?bangumiId=3177&subgroupid=615. Wait for 5 seconds.
[2023-10-14 14:28:48] ERROR     Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/api/rss.py", line 199, in subscribe
    resp = collector.subscribe_season(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/manager/collector.py", line 56, in subscribe_season
    result = engine.download_bangumi(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/rss/engine.py", line 136, in download_bangumi
    torrents = req.get_torrents(
               ^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 29, in get_torrents
    if re.search(_filter, _title) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 982, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 457, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 867, in _parse
    raise source.error("missing ), unterminated subpattern",
re.error: missing ), unterminated subpattern at position 39
[2023-10-14 14:30:23] WARNING:  Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='192.168.5.15', port=5016): Read timed out. (read timeout=10)")': /
[2023-10-14 14:30:36] WARNING:  Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='192.168.5.15', port=5016): Read timed out. (read timeout=3.1)")': /
[2023-10-14 14:31:00] WARNING:  Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='192.168.5.15', port=5016): Read timed out. (read timeout=10)")': /
[2023-10-14 14:31:13] WARNING:  Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='192.168.5.15', port=5016): Read timed out. (read timeout=3.1)")': /
```

**Comment by xfrqh** [comment]
可能是我的代理设置的问题，填写了错误的用户名、密码。已经订阅上了。

**Comment by xfrqh** [comment]
应该不是网络问题，因为其他番剧都能正常订阅。

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/73733485/451bfa4e-5fb9-4c2c-b74b-eed0503689cd)

**Comment by EstrellaXD** [comment]
请在过滤规则中以正则的形式写规则

**Comment by xfrqh** [comment]
> 请在过滤规则中以正则的形式写规则

想**请教**一下。为什么这些不符合正则的形式，纯字符串不是正则的形式中的一种吗？

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/73733485/4fdcf87b-b1e7-4dbc-8a5f-2df42a998e78)

**Comment by EstrellaXD** [comment]
@xfrqh 特殊符号添加转译

**Comment by xfrqh** [comment]
> @xfrqh 特殊符号添加转译

豁然开朗😆，谢谢指导😉
![code](https://github.com/EstrellaXD/Auto_Bangumi/assets/73733485/5cd99f52-d7a6-4890-a088-ac2d2d895855)
