### ISSUE TITLE
[错误报告] RSS解析下载时报错：Exception in thread Thread-X 

### ISSUE THREAD

**Issue by byoukinn** [EstrellaXD/Auto_Bangumi#592]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.10

### 问题类型

程序运行问题

### 问题描述

[当天rss.txt](https://github.com/EstrellaXD/Auto_Bangumi/files/13064130/rss.txt)

环境：window server的docker-compose

重启ab后查看webui日志不进行添加种子行为，查看docker后台，有如标题的报错。
观察日志，应该是rss获取种子部分有变动导致报错，附件为当天的rss，看不出有什么问题。

注：日志中有些连接错误，`mydownloader.com`是我提问时替换的虚假域名，实际域名上是连接上了的，这部分报错属于误导信息。

### 发生问题时系统日志

```bash
2023-10-23 01:58:47 [2023-10-23 01:58:47] DEBUG:    Using selector: EpollSelector
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:     Started server process [7]
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:     Waiting for application startup.
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:     
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:                     _        ____                                    _
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:          /\        | |      |  _ \                                  (_)
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:                                                 __/ |
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:                                                |___/
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:     Version 3.1.10  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:     Starting AutoBangumi...
2023-10-23 01:58:47 [2023-10-23 01:58:47] INFO:     Config loaded
2023-10-23 01:58:47 [2023-10-23 01:58:47] DEBUG:    Starting new HTTP connection (1): mydownloader.com
2023-10-23 01:58:51 [2023-10-23 01:58:51] DEBUG:    http://mydownloader.com "GET / HTTP/1.1" 200 639
2023-10-23 01:58:52 [2023-10-23 01:58:52] DEBUG:    Re-initializing context...
2023-10-23 01:58:56 [2023-10-23 01:58:56] DEBUG:    [Downloader] Authed.
2023-10-23 01:58:56 [2023-10-23 01:58:56] INFO:     Program running.
2023-10-23 01:58:56 [2023-10-23 01:58:56] INFO:     Application startup complete.
2023-10-23 01:58:56 [2023-10-23 01:58:56] INFO:     Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
2023-10-23 01:59:01 [2023-10-23 01:59:01] WARNING:  Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f0725be7dd0>: Failed to resolve 'mydownloader.com' ([Errno -3] Try again)")': /
2023-10-23 01:59:03 [2023-10-23 01:59:03] WARNING:  Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f0725da2b10>: Failed to resolve 'mydownloader.com' ([Errno -3] Try again)")': /api/v2/auth/login
2023-10-23 01:59:03 [2023-10-23 01:59:03] DEBUG:    [Downloader] Authed.
2023-10-23 01:59:03 [2023-10-23 01:59:03] DEBUG:    [Renamer] Start rename process.
2023-10-23 01:59:04 [2023-10-23 01:59:04] DEBUG:    [Renamer] Rename process finished.
2023-10-23 01:59:10 [2023-10-23 01:59:10] WARNING:  Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f0725bf3490>: Failed to resolve 'mydownloader.com' ([Errno -3] Try again)")': /api/v2/auth/login
2023-10-23 01:59:10 [2023-10-23 01:59:10] DEBUG:    [Downloader] Authed.
2023-10-23 01:59:15 [2023-10-23 01:59:15] WARNING:  [Network] Cannot connect to https://mikanime.tv/RSS/MyBangumi?token=SvifR%2fRV02RHNZJoYSoooR%2fbCCzLERZPpevF0%2bB9vrs%3d. Wait for 5 seconds.
2023-10-23 01:59:25 Exception in thread Thread-4 (rss_loop):
2023-10-23 01:59:25 Traceback (most recent call last):
2023-10-23 01:59:25   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
2023-10-23 01:59:25     self.run()
2023-10-23 01:59:25   File "/usr/lib/python3.11/threading.py", line 982, in run
2023-10-23 01:59:25     self._target(*self._args, **self._kwargs)
2023-10-23 01:59:25   File "/app/module/core/sub_thread.py", line 27, in rss_loop
2023-10-23 01:59:25     self.analyser.rss_to_data(rss, engine)
2023-10-23 01:59:25   File "/app/module/rss/analyser.py", line 69, in rss_to_data
2023-10-23 01:59:25     rss_torrents = self.get_rss_torrents(rss.url, full_parse)
2023-10-23 01:59:25                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-23 01:59:25   File "/app/module/rss/analyser.py", line 40, in get_rss_torrents
2023-10-23 01:59:25     rss_torrents = req.get_torrents(rss_link)
2023-10-23 01:59:25                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-23 01:59:25   File "/app/module/network/request_contents.py", line 29, in get_torrents
2023-10-23 01:59:25     if re.search(_filter, _title) is None:
2023-10-23 01:59:25        ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-23 01:59:25   File "/usr/lib/python3.11/re/__init__.py", line 176, in search
2023-10-23 01:59:25     return _compile(pattern, flags).search(string)
2023-10-23 01:59:25            ^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-23 01:59:25   File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
2023-10-23 01:59:25     p = _compiler.compile(pattern, flags)
2023-10-23 01:59:25         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-23 01:59:25   File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
2023-10-23 01:59:25     p = _parser.parse(p, flags)
2023-10-23 01:59:25         ^^^^^^^^^^^^^^^^^^^^^^^
2023-10-23 01:59:25   File "/usr/lib/python3.11/re/_parser.py", line 982, in parse
2023-10-23 01:59:25     p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
2023-10-23 01:59:25         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-23 01:59:25   File "/usr/lib/python3.11/re/_parser.py", line 457, in _parse_sub
2023-10-23 01:59:25     itemsappend(_parse(source, state, verbose, nested + 1,
2023-10-23 01:59:25                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-23 01:59:25   File "/usr/lib/python3.11/re/_parser.py", line 867, in _parse
2023-10-23 01:59:25     raise source.error("missing ), unterminated subpattern",
2023-10-23 01:59:25 re.error: missing ), unterminated subpattern at position 29
2023-10-23 02:00:08 [2023-10-23 02:00:08] DEBUG:    [Downloader] Authed.
2023-10-23 02:00:08 [2023-10-23 02:00:08] DEBUG:    [Renamer] Start rename process.
2023-10-23 02:00:09 [2023-10-23 02:00:09] DEBUG:    [Renamer] Rename process finished.
2023-10-23 02:01:12 [2023-10-23 02:01:12] DEBUG:    [Downloader] Authed.
2023-10-23 02:01:12 [2023-10-23 02:01:12] DEBUG:    [Renamer] Start rename process.
2023-10-23 02:01:12 [2023-10-23 02:01:12] DEBUG:    [Renamer] Rename process finished.
2023-10-23 02:02:15 [2023-10-23 02:02:15] DEBUG:    [Downloader] Authed.
2023-10-23 02:02:15 [2023-10-23 02:02:15] DEBUG:    [Renamer] Start rename process.
2023-10-23 02:02:16 [2023-10-23 02:02:16] DEBUG:    [Renamer] Rename process finished.
2023-10-23 02:03:22 [2023-10-23 02:03:22] DEBUG:    [Downloader] Authed.
2023-10-23 02:03:22 [2023-10-23 02:03:22] DEBUG:    [Renamer] Start rename process.
2023-10-23 02:03:23 [2023-10-23 02:03:23] DEBUG:    [Renamer] Rename process finished.
2023-10-23 02:04:28 [2023-10-23 02:04:28] WARNING:  Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f07255732d0>: Failed to resolve 'mydownloader.com' ([Errno -3] Try again)")': /
2023-10-23 02:04:33 [2023-10-23 02:04:33] WARNING:  Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f0725580dd0>: Failed to resolve 'mydownloader.com' ([Errno -3] Try again)")': /api/v2/auth/login
2023-10-23 02:04:33 [2023-10-23 02:04:33] DEBUG:    [Downloader] Authed.
2023-10-23 02:04:33 [2023-10-23 02:04:33] DEBUG:    [Renamer] Start rename process.
2023-10-23 02:04:34 [2023-10-23 02:04:34] DEBUG:    [Renamer] Rename process finished.
2023-10-23 02:05:41 [2023-10-23 02:05:41] DEBUG:    [Downloader] Authed.
2023-10-23 02:05:41 [2023-10-23 02:05:41] DEBUG:    [Renamer] Start rename process.
2023-10-23 02:05:42 [2023-10-23 02:05:42] DEBUG:    [Renamer] Rename process finished.
```

**Comment by EstrellaXD** [comment]
请使用规范的正则语法
