### ISSUE TITLE
[错误报告]本地部署时缺少了config文件夹，导致config.json建不出来

### ISSUE THREAD

**Issue by RimoChan** [EstrellaXD/Auto_Bangumi#604]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.10

### 问题类型

其他问题

### 问题描述

按照 https://www.autobangumi.org/deploy/local.html 的做法部署的，但是最后一步会挂。应该是要在config.py里加一个mkdir？

### 发生问题时系统日志

```bash
(env) R:\Auto_Bangumi-app-v3.1.10\src>python main.py
Traceback (most recent call last):
  File "R:\Auto_Bangumi-app-v3.1.10\src\main.py", line 9, in <module>
    from module.api import v1
  File "R:\Auto_Bangumi-app-v3.1.10\src\module\api\__init__.py", line 3, in <module>
    from .auth import router as auth_router
  File "R:\Auto_Bangumi-app-v3.1.10\src\module\api\auth.py", line 9, in <module>
    from module.security.api import (
  File "R:\Auto_Bangumi-app-v3.1.10\src\module\security\api.py", line 4, in <module>
    from module.database import Database
  File "R:\Auto_Bangumi-app-v3.1.10\src\module\database\__init__.py", line 1, in <module>
    from .combine import Database
  File "R:\Auto_Bangumi-app-v3.1.10\src\module\database\combine.py", line 6, in <module>
    from .engine import engine as e
  File "R:\Auto_Bangumi-app-v3.1.10\src\module\database\engine.py", line 3, in <module>
    from module.conf import DATA_PATH
  File "R:\Auto_Bangumi-app-v3.1.10\src\module\conf\__init__.py", line 3, in <module>
    from .config import VERSION, settings
  File "R:\Auto_Bangumi-app-v3.1.10\src\module\conf\config.py", line 87, in <module>
    settings = Settings()
  File "R:\Auto_Bangumi-app-v3.1.10\src\module\conf\config.py", line 36, in __init__
    self.init()
  File "R:\Auto_Bangumi-app-v3.1.10\src\module\conf\config.py", line 54, in init
    self.save()
  File "R:\Auto_Bangumi-app-v3.1.10\src\module\conf\config.py", line 48, in save
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'R:\\Auto_Bangumi-app-v3.1.10\\src\\config\\config.json'
```

**Comment by gdm257** [comment]
手动创建 `config` 文件夹，再里边手动创建 `config.json` 文件，内容为一对花括号 `{}`，保存

也可命令行来做

```bash
mkdir config
echo '{}' > config/config.json
```

**Comment by EstrellaXD** [comment]
文档已更新

**Comment by RimoChan** [comment]
等等，怎么是更新文档，不能去with open前面加一个mkdir吗？
