### ISSUE TITLE
[错误报告]登录的时候无法登录

### ISSUE THREAD

**Issue by nayaku** [EstrellaXD/Auto_Bangumi#608]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.10

### 问题类型

WebUI

### 问题描述

程序登录时候出问题

### 发生问题时系统日志

```bash
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:     Started server process [7]
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:     Waiting for application startup.
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:     
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:                     _        ____                                    _
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:          /\        | |      |  _ \                                  (_)
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:                                                 __/ |
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:                                                |___/
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:     Version 3.1.10  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:     Starting AutoBangumi...
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:     Config loaded
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:     Program running.
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:     Application startup complete.
2023-10-29 14:14:34 AutoBangumi  | [2023-10-29 14:14:34] INFO:     Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
2023-10-29 14:15:00 AutoBangumi  | [2023-10-29 14:15:00] ERROR     Exception in ASGI application
2023-10-29 14:15:00 AutoBangumi  | Traceback (most recent call last):
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2023-10-29 14:15:00 AutoBangumi  |     result = await app(  # type: ignore[func-returns-value]
2023-10-29 14:15:00 AutoBangumi  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-10-29 14:15:00 AutoBangumi  |     return await self.app(scope, receive, send)
2023-10-29 14:15:00 AutoBangumi  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
2023-10-29 14:15:00 AutoBangumi  |     raise exc from None
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
2023-10-29 14:15:00 AutoBangumi  |     await self.app(scope, inner_receive, inner_send)
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
2023-10-29 14:15:00 AutoBangumi  |     await super().__call__(scope, receive, send)
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2023-10-29 14:15:00 AutoBangumi  |     await self.middleware_stack(scope, receive, send)
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-10-29 14:15:00 AutoBangumi  |     raise exc
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-10-29 14:15:00 AutoBangumi  |     await self.app(scope, receive, _send)
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-10-29 14:15:00 AutoBangumi  |     raise exc
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-10-29 14:15:00 AutoBangumi  |     await self.app(scope, receive, sender)
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-10-29 14:15:00 AutoBangumi  |     raise e
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-10-29 14:15:00 AutoBangumi  |     await self.app(scope, receive, send)
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2023-10-29 14:15:00 AutoBangumi  |     await route.handle(scope, receive, send)
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2023-10-29 14:15:00 AutoBangumi  |     await self.app(scope, receive, send)
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2023-10-29 14:15:00 AutoBangumi  |     response = await func(request)
2023-10-29 14:15:00 AutoBangumi  |                ^^^^^^^^^^^^^^^^^^^
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
2023-10-29 14:15:00 AutoBangumi  |     raw_response = await run_endpoint_function(
2023-10-29 14:15:00 AutoBangumi  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
2023-10-29 14:15:00 AutoBangumi  |     return await dependant.call(**values)
2023-10-29 14:15:00 AutoBangumi  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-29 14:15:00 AutoBangumi  |   File "/app/module/api/auth.py", line 25, in login
2023-10-29 14:15:00 AutoBangumi  |     resp = auth_user(user)
2023-10-29 14:15:00 AutoBangumi  |            ^^^^^^^^^^^^^^^
2023-10-29 14:15:00 AutoBangumi  |   File "/app/module/security/api.py", line 48, in auth_user
2023-10-29 14:15:00 AutoBangumi  |     resp = db.user.auth_user(user)
2023-10-29 14:15:00 AutoBangumi  |            ^^^^^^^^^^^^^^^^^^^^^^^
2023-10-29 14:15:00 AutoBangumi  |   File "/app/module/database/user.py", line 31, in auth_user
2023-10-29 14:15:00 AutoBangumi  |     if not verify_password(user.password, result.password):
2023-10-29 14:15:00 AutoBangumi  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-29 14:15:00 AutoBangumi  |   File "/app/module/security/jwt.py", line 56, in verify_password
2023-10-29 14:15:00 AutoBangumi  |     return app_pwd_context.verify(plain_password, hashed_password)
2023-10-29 14:15:00 AutoBangumi  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/passlib/context.py", line 2347, in verify
2023-10-29 14:15:00 AutoBangumi  |     return record.verify(secret, hash, **kwds)
2023-10-29 14:15:00 AutoBangumi  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/passlib/utils/handlers.py", line 787, in verify
2023-10-29 14:15:00 AutoBangumi  |     validate_secret(secret)
2023-10-29 14:15:00 AutoBangumi  |   File "/usr/lib/python3.11/site-packages/passlib/utils/handlers.py", line 122, in validate_secret
2023-10-29 14:15:00 AutoBangumi  |     raise exc.ExpectedStringError(secret, "secret")
2023-10-29 14:15:00 AutoBangumi  | TypeError: secret must be unicode or bytes, not None
```

**Comment by EstrellaXD** [comment]
登陆时没有输入密码？

**Comment by nayaku** [comment]
输入密码了，但是没有提示密码不正确，而是弹出一个空内容的错误消息框。



---原始邮件---
发件人: "Estrella ***@***.***&gt;
发送时间: 2023年10月31日(周二) 晚上9:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [EstrellaXD/Auto_Bangumi] [错误报告]登录的时候无法登录 (Issue #608)




 
登陆时没有输入密码？

**Comment by MikuQing** [comment]
我也遇到了一样的问题，版本为新的3.1.11，并再删除重装后还是一样的问题，请问你有解决吗

**Comment by EstrellaXD** [comment]
@jsp1256 请提供一下 `data.db` 文件，应该存放在绑定的 `data` 文件夹下

**Comment by jsp1256** [comment]
> @jsp1256 请提供一下 `data.db` 文件，应该存放在绑定的 `data` 文件夹下，以及输入的密码是否包含非标准 unicode 字符
目前确认密码没有使用非标准的unicode字符
[Uploading data.db.zip…]()

**Comment by EstrellaXD** [comment]
> > @jsp1256 请提供一下 `data.db` 文件，应该存放在绑定的 `data` 文件夹下，以及输入的密码是否包含非标准 unicode 字符
> 
> 目前确认密码没有使用非标准的unicode字符 [data.db.zip](https://github.com/EstrellaXD/Auto_Bangumi/files/13582103/data.db.zip)

从数据库上看是正常的，方便描述一下产生报错的情况么，并进行一下浏览器debug么。在浏览器的调试界面（F12）又一个Network tab，清空后登录 AB 应该会有个报错的 API 选项，复制报错的`auth`api成 cURL 选项后提供诊断。

**Comment by jsp1256** [comment]
> > > @jsp1256 请提供一下 `data.db` 文件，应该存放在绑定的 `data` 文件夹下，以及输入的密码是否包含非标准 unicode 字符
> > 
> > 
> > 目前确认密码没有使用非标准的unicode字符 [data.db.zip](https://github.com/EstrellaXD/Auto_Bangumi/files/13582103/data.db.zip)
> 
> 从数据库上看是正常的，方便描述一下产生报错的情况么，并进行一下浏览器debug么。在浏览器的调试界面（F12）又一个Network tab，清空后登录 AB 应该会有个报错的 API 选项，复制报错的`auth`api成 cURL 选项后提供诊断。
错误是在第一次部署没多久的第二天的中午产生的，截至目前，日志中没有再报告此类错误。
浏览器F12的network目前看都是200 OK，已尝试多次，暂时未复现该错误。
也许该错误在我的平台上非必现，目前尚未找到复现条件，正在尝试复现问题中。
