### ISSUE TITLE
[错误报告]Failed to refresh poster

### ISSUE THREAD

**Issue by JourneyBean** [EstrellaXD/Auto_Bangumi#630]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.11

### 问题类型

程序运行问题

### 问题描述

# Failed to refresh poster

当我点击“Refresh Poster”时，发生了以下问题：

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/14137731/57735b98-a194-447d-a66a-b4670b72301b)

我将日志级别改成了DEBUG，提取到了日志。

仅仅当我代理不稳定，可能花好几秒才能获得响应时，才容易发生此现象。（直接curl，平均要花约7秒才返回数据）

一些提议：

- 希望对该异常进行相关处理
- module.network.request_url.RequestURL中设置5s的超时会不会有点太严苛了，希望能适当提高超时时间

### 发生问题时系统日志

```bash
[2023-12-03 23:11:45] DEBUG:    [Network] Cannot connect to https://api.themoviedb.org/3/search/tv?api_key=32b19d6a05b512190a056fa4e747cbbc&page=1&query=间谍过家家&include_adult=false. Wait for 5 seconds.
[2023-12-03 23:11:55] DEBUG:    [Network] Cannot connect to https://api.themoviedb.org/3/search/tv?api_key=32b19d6a05b512190a056fa4e747cbbc&page=1&query=间谍过家家&include_adult=false. Wait for 5 seconds.
[2023-12-03 23:12:05] DEBUG:    [Network] Cannot connect to https://api.themoviedb.org/3/search/tv?api_key=32b19d6a05b512190a056fa4e747cbbc&page=1&query=间谍过家家&include_adult=false. Wait for 5 seconds.
[2023-12-03 23:12:05] ERROR     [Network] Unable to connect to https://api.themoviedb.org/3/search/tv?api_key=32b19d6a05b512190a056fa4e747cbbc&page=1&query=间谍过家家&include_adult=false, Please check your network settings
[2023-12-03 23:12:05] ERROR     Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/api/bangumi.py", line 116, in refresh_poster
    resp = manager.refresh_poster()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/manager/torrent.py", line 137, in refresh_poster
    TitleParser().tmdb_poster_parser(bangumi)
  File "/app/module/parser/title_parser.py", line 47, in tmdb_poster_parser
    tmdb_info = tmdb_parser(bangumi.official_title, settings.rss_parser.language)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/parser/analyser/tmdb_parser.py", line 62, in tmdb_parser
    contents = req.get_json(url).get("results")
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by EstrellaXD** [comment]
Closing stale bug report (older than 2 years). Please reopen if still relevant.
