### ISSUE TITLE
[错误报告]请在此处简单描述你的问题

### ISSUE THREAD

**Issue by parallels123** [EstrellaXD/Auto_Bangumi#680]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

Version: 3.1.12

### 问题类型

程序运行问题

### 问题描述

程序没有办法正常启动，尝试重装多次后仍未解决

### 发生问题时系统日志

```bash
[2024-01-29 00:29:41] INFO:     Started server process [7]
[2024-01-29 00:29:41] INFO:     Waiting for application startup.
[2024-01-29 00:29:41] INFO:     
[2024-01-29 00:29:41] INFO:                     _        ____                                    _
[2024-01-29 00:29:41] INFO:          /\        | |      |  _ \                                  (_)
[2024-01-29 00:29:41] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _
[2024-01-29 00:29:41] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2024-01-29 00:29:41] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2024-01-29 00:29:41] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2024-01-29 00:29:41] INFO:                                                 __/ |
[2024-01-29 00:29:41] INFO:                                                |___/
[2024-01-29 00:29:41] INFO:     Version 3.1.12  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2024-01-29 00:29:41] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2024-01-29 00:29:41] INFO:     Starting AutoBangumi...
[2024-01-29 00:29:42] INFO:     [Core] No db file exists, create database file.
[2024-01-29 00:29:42] INFO:     Application startup complete.
[2024-01-29 00:29:42] INFO:     Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
[2024-01-29 00:31:12] INFO:     Config loaded
[2024-01-29 00:31:12] INFO:     Config updated
[2024-01-29 00:31:12] INFO:     Config loaded
[2024-01-29 00:31:12] WARNING:  Program failed to start.
[2024-01-29 00:31:25] INFO:     Config loaded
[2024-01-29 00:31:25] INFO:     Config updated
[2024-01-29 00:31:25] INFO:     Config loaded
[2024-01-29 00:31:25] WARNING:  Program failed to start.
[2024-01-29 00:31:54] ERROR     [Network] Unable to connect to https://mikanani.me/RSS/Search?searchstr=modu, Please check your network settings
[2024-01-29 00:31:54] WARNING:  [Network] Failed to get torrents: https://mikanani.me/RSS/Search?searchstr=modu
[2024-01-29 00:31:57] ERROR     [Network] Unable to connect to https://mikanani.me/RSS/Search?searchstr=魔都, Please check your network settings
[2024-01-29 00:31:57] WARNING:  [Network] Failed to get torrents: https://mikanani.me/RSS/Search?searchstr=魔都
[2024-01-29 00:32:06] ERROR     [Network] Unable to connect to https://mikanani.me/RSS/Search?searchstr=魔都, Please check your network settings
[2024-01-29 00:32:06] WARNING:  [Network] Failed to get torrents: https://mikanani.me/RSS/Search?searchstr=魔都
[2024-01-29 00:35:37] INFO:     Config loaded
[2024-01-29 00:35:37] INFO:     Config updated
[2024-01-29 00:35:37] INFO:     Config loaded
[2024-01-29 00:35:37] WARNING:  Program failed to start.
[2024-01-29 00:36:06] ERROR     [Network] Unable to connect to https://mikanani.me/RSS/Search?searchstr=魔都, Please check your network settings
[2024-01-29 00:36:06] WARNING:  [Network] Failed to get torrents: https://mikanani.me/RSS/Search?searchstr=魔都
[2024-01-29 00:38:55] WARNING:  Cannot parse [动漫国字幕组&VCB-Studio] 刀剑神域 Progressive 阴沉薄暮的诙谐曲 / SAO Progressive - Kuraki Yuuyami no Scherzo 10-bit 1080p HEVC BDRip [Fin].
[2024-01-29 00:38:55] WARNING:  Cannot parse [动漫国字幕组&VCB-Studio] 刀剑神域 Progressive 无星夜的咏叹调 / SAO Progressive - Hoshinaki Yoru no Aria 10-bit 1080p HEVC BDRip [Reseed Fin].
[2024-01-29 00:39:20] ERROR     [Network] Unable to connect to https://api.themoviedb.org/3/search/tv?api_key=32b19d6a05b512190a056fa4e747cbbc&page=1&query=刀剑神域 Progressive 阴沉薄暮的诙谐曲&include_adult=false, Please check your network settings
[2024-01-29 00:39:20] ERROR     Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/sse_starlette/sse.py", line 233, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/usr/lib/python3.11/site-packages/sse_starlette/sse.py", line 236, in wrap
    await func()
  File "/usr/lib/python3.11/site-packages/sse_starlette/sse.py", line 221, in stream_response
    async for data in self.body_iterator:
  File "/usr/lib/python3.11/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/starlette/concurrency.py", line 53, in _next
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 38, in analyse_keyword
    bangumi = self.torrent_to_data(torrent=torrent, rss=rss_item)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/rss/analyser.py", line 62, in torrent_to_data
    self.official_title_parser(bangumi=bangumi, rss=rss, torrent=torrent)
  File "/app/module/rss/analyser.py", line 25, in official_title_parser
    tmdb_title, season, year, poster_link = self.tmdb_parser(
                                            ^^^^^^^^^^^^^^^^^
  File "/app/module/parser/title_parser.py", line 35, in tmdb_parser
    tmdb_info = tmdb_parser(title, language)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/parser/analyser/tmdb_parser.py", line 62, in tmdb_parser
    contents = req.get_json(url).get("results")
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
[2024-01-29 00:39:24] ERROR     [Network] Unable to connect to https://nyaa.si/?page=rss&q=刀剑&c=0_0&f=0, Please check your network settings
[2024-01-29 00:39:24] WARNING:  [Network] Failed to get torrents: https://nyaa.si/?page=rss&q=刀剑&c=0_0&f=0
[2024-01-29 00:42:20] INFO:     Config loaded
[2024-01-29 00:42:20] INFO:     Config updated
[2024-01-29 00:42:20] INFO:     Config loaded
[2024-01-29 00:42:20] WARNING:  Program failed to start.
```

**Comment by tabjy** [comment]
`api.themoviedb.org` 可能被墙，可以参考：[#13](https://github.com/msterzhang/onelist/issues/13)
