### ISSUE TITLE
[错误报告] 重启容器后之前的海报无法显示

### ISSUE THREAD

**Issue by ifei-ting** [EstrellaXD/Auto_Bangumi#714]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.12

### 问题类型

WebUI

### 问题描述

重启容易以后之前的海报无法显示，新下载的海报则不受影响，日志未见报错。
![微信截图_20240308211447](https://github.com/EstrellaXD/Auto_Bangumi/assets/42956222/3a594899-4444-485b-883f-0cfc93be869d)

### 发生问题时系统日志

```bash
[2024-03-08 16:48:37] INFO:     Started server process [7]
[2024-03-08 16:48:37] INFO:     Waiting for application startup.
[2024-03-08 16:48:37] INFO:     
[2024-03-08 16:48:37] INFO:                     _        ____                                    _
[2024-03-08 16:48:37] INFO:          /\        | |      |  _ \                                  (_)
[2024-03-08 16:48:37] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _
[2024-03-08 16:48:37] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2024-03-08 16:48:37] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2024-03-08 16:48:37] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2024-03-08 16:48:37] INFO:                                                 __/ |
[2024-03-08 16:48:37] INFO:                                                |___/
[2024-03-08 16:48:37] INFO:     Version 3.1.12  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2024-03-08 16:48:37] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2024-03-08 16:48:37] INFO:     Starting AutoBangumi...
[2024-03-08 16:48:38] INFO:     [Core] Database updated.
[2024-03-08 16:48:38] INFO:     Config loaded
[2024-03-08 16:48:39] INFO:     Program running.
[2024-03-08 16:48:39] INFO:     Application startup complete.
[2024-03-08 16:48:39] INFO:     Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
[2024-03-08 16:55:40] INFO:     [Sakurato] Oroka na Tenshi wa Akuma to Odoru [09][HEVC-10bit 1080p AAC][CHS&CHT].mkv >> 愚蠢天使与恶魔共舞 S01E09.mkv
[2024-03-08 17:01:41] INFO:     [Sakurato] Itai No Wa Iya Nano De Bougyoryoku Ni Kyokufuri Shitai To Omoimasu. [03][HEVC-10bit 1080P AAC][CHS&CHT].mkv >> 因为太怕痛就全点防御力了 S02E03.mkv
[2024-03-08 17:10:43] INFO:     [Sakurato] Itai No Wa Iya Nano De Bougyoryoku Ni Kyokufuri Shitai To Omoimasu. [02][HEVC-10bit 1080P AAC][CHS&CHT].mkv >> 因为太怕痛就全点防御力了 S02E02.mkv
[2024-03-08 17:13:44] INFO:     [Sakurato] Itai No Wa Iya Nano De Bougyoryoku Ni Kyokufuri Shitai To Omoimasu. [05][HEVC-10bit 1080P AAC][CHS&CHT].mkv >> 因为太怕痛就全点防御力了 S02E05.mkv
[2024-03-08 17:47:50] INFO:     [Sakurato] Itai No Wa Iya Nano De Bougyoryoku Ni Kyokufuri Shitai To Omoimasu. [01][HEVC-10bit 1080P AAC][CHS&CHT].mkv >> 因为太怕痛就全点防御力了 S02E01.mkv
[2024-03-08 17:58:08] INFO:     Config loaded
[2024-03-08 17:58:08] INFO:     Config updated
[2024-03-08 17:58:08] INFO:     Config loaded
[2024-03-08 17:58:08] INFO:     Program running.
```

**Comment by shininome** [comment]
@ifei-ting 可以尝试删除data路径下的海报文件

**Comment by shininome** [comment]
@shininome posters文件夹整个删除呢

**Comment by ifei-ting** [comment]
> @shininome posters文件夹整个删除呢

删除posters文件夹又重启容器后，没有报错了。但是很有趣的是，海报墙完全保持了之前的显示状态，（即如上面截图中：一张显示，其余不显示），删除浏览器cookies也一样。

**Comment by ifei-ting** [comment]
> > @shininome posters文件夹整个删除呢
> 
> 删除posters文件夹又重启容器后，没有报错了。但是很有趣的是，海报墙完全保持了之前的显示状态，（即如上面截图中：一张显示，其余不显示），删除浏览器cookies也一样。

等待片刻后，全部不显示了，而且报错。


[2024-03-08 21:54:19] INFO:     Started server process [7]
[2024-03-08 21:54:19] INFO:     Waiting for application startup.
[2024-03-08 21:54:19] INFO:     
[2024-03-08 21:54:19] INFO:                     _        ____                                    _
[2024-03-08 21:54:19] INFO:          /\        | |      |  _ \                                  (_)
[2024-03-08 21:54:19] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _
[2024-03-08 21:54:19] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2024-03-08 21:54:19] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2024-03-08 21:54:19] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2024-03-08 21:54:19] INFO:                                                 __/ |
[2024-03-08 21:54:19] INFO:                                                |___/
[2024-03-08 21:54:19] INFO:     Version 3.1.12  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2024-03-08 21:54:19] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2024-03-08 21:54:19] INFO:     Starting AutoBangumi...
[2024-03-08 21:54:19] INFO:     Config loaded
[2024-03-08 21:54:19] INFO:     Program running.
[2024-03-08 21:54:19] INFO:     Application startup complete.
[2024-03-08 21:54:19] INFO:     Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
[2024-03-08 22:07:31] ERROR     Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/responses.py", line 338, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path data/posters/051ad79c.jpg does not exist.

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/42956222/99e49f49-ad56-4689-a280-118b769ba934)

**Comment by SlyFZG** [comment]
我要遇到一样的问题，起先是因为订阅的动漫在qb里下再多了，于是我按照提示删除下载任务后重启AB，重启后就出现海报缺失的画面，如图
![{CEC01C22-8426-49D5-BF67-3DE9C43C31A8}](https://github.com/EstrellaXD/Auto_Bangumi/assets/35863677/b55ebcf8-9dac-495e-be72-507c2fcb80cf)

**Comment by myin16** [comment]
我也是这个问题，尝试了删除poster下所有文件和删除poster整个文件夹都不行

**Comment by 913772462** [comment]
确认遇到相同问题，我把数据库弄到本地后，打开看了一下，他这个用的是sqlite，在正常的时候即重启容器前，poster_link一项均为本地目录，例如"posters/6db5e106.jpg"，但是重启容器后poster_link一项均会变成网络目录的一张图片，我遇到的情况应该是变成了mikan的一个地址，拷贝此地址，无法正确访问，问题应该出在数据库里的这一项如何变成网络地址这一点上

**Comment by 913772462** [comment]
> 确认遇到相同问题，我把数据库弄到本地后，打开看了一下，他这个用的是sqlite，在正常的时候即重启容器前，poster_link一项均为本地目录，例如"posters/6db5e106.jpg"，但是重启容器后poster_link一项均会变成网络目录的一张图片，我遇到的情况应该是变成了mikan的一个地址，拷贝此地址，无法正确访问，问题应该出在数据库里的这一项如何变成网络地址这一点上

有时间了，又排查了一下，容器重启后poster_link一项均会变成，'https://mikanani.me' +原本正常的图片路径(例如:posters/6db5e106.jpg变成了https://mikanani.meposters/6db5e106.jpg)，这个就不好说是停止容器出的错误还是启动容器出的错误了，用python写了段代码，如果出现的问题一样可以先临时顶一下，等问题修复。

```Python
import sqlite3

# 连接数据库-替换为自己数据库的路径(我加了r表示这是个路径，不需要解决直接复制路径造成的转义字符的问题)
dir = r'data.db'
conn = sqlite3.connect(dir)

# 创建一个SQL执行对象
cursor = conn.cursor()

# 执行查询从bangumi表中获取所有poster_link信息
cursor.execute("SELECT poster_link FROM bangumi")

# 将所有poster_link的数据读取出来，将其中的'https://mikanani.me'替换为''
rows = cursor.fetchall()
for row in rows:
    new_row = row[0].replace('https://mikanani.me', '')
    print(new_row)
    cursor.execute("UPDATE bangumi SET poster_link = ? WHERE poster_link = ?", (new_row, row[0]))

# 提交变更
conn.commit()

# 关闭SQL执行对象和数据库
cursor.close()
conn.close()
```

**Comment by EstrellaXD** [comment]
3.3.0 已修复：海报缓存持久化在 data 卷（data/posters），并修复了属主迁移中断后不自愈的问题；重启容器海报不再丢失。
