### ISSUE TITLE
[番剧补全失效]使用的是最新版本docker 看docker日志有报错

### ISSUE THREAD

**Issue by jiangshuai377** [EstrellaXD/Auto_Bangumi#750]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

"org.opencontainers.image.version": "3.1.12"

### 问题类型

WebUI

### 问题描述

[番剧补全失效]

### 发生问题时系统日志

```bash
2024-04-18 23:52:52 [2024-04-18 23:52:52] INFO:     Config loaded
2024-04-18 23:52:52 [2024-04-18 23:52:52] INFO:     Config updated
2024-04-18 23:52:52 [2024-04-18 23:52:52] INFO:     Config loaded
2024-04-18 23:52:52 [2024-04-18 23:52:52] INFO:     Program running.
2024-04-18 23:52:54 [2024-04-18 23:52:54] INFO:     Start collecting full season...
2024-04-18 23:52:54 [2024-04-18 23:52:54] INFO:     Start collecting 关于我转生变成史莱姆这档事 Season 3...
2024-04-18 23:52:55 Exception in thread Thread-6 (rss_loop):
2024-04-18 23:52:55 Traceback (most recent call last):
2024-04-18 23:52:55   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
2024-04-18 23:52:55     self.run()
2024-04-18 23:52:55   File "/usr/lib/python3.11/threading.py", line 982, in run
2024-04-18 23:52:55     self._target(*self._args, **self._kwargs)
2024-04-18 23:52:55   File "/app/module/core/sub_thread.py", line 31, in rss_loop
2024-04-18 23:52:55     eps_complete()
2024-04-18 23:52:55   File "/app/module/manager/collector.py", line 69, in eps_complete
2024-04-18 23:52:55     collector.collect_season(data)
2024-04-18 23:52:55   File "/app/module/manager/collector.py", line 21, in collect_season
2024-04-18 23:52:55     if self.add_torrent(torrents, bangumi):
2024-04-18 23:52:55        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-18 23:52:55   File "/app/module/downloader/download_client.py", line 138, in add_torrent
2024-04-18 23:52:55     if self.client.add_torrents(
2024-04-18 23:52:55        ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-18 23:52:55   File "/app/module/downloader/client/qb_downloader.py", line 86, in add_torrents
2024-04-18 23:52:55     resp = self._client.torrents_add(
2024-04-18 23:52:55            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-18 23:52:55   File "/usr/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 91, in wrapper
2024-04-18 23:52:55     return func(client, *args, **kwargs)
2024-04-18 23:52:55            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-18 23:52:55   File "/usr/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 1306, in torrents_add
2024-04-18 23:52:55     return self._post(
2024-04-18 23:52:55            ^^^^^^^^^^^
2024-04-18 23:52:55   File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 390, in _post
2024-04-18 23:52:55     return self._request_manager(
2024-04-18 23:52:55            ^^^^^^^^^^^^^^^^^^^^^^
2024-04-18 23:52:55   File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 465, in _request_manager
2024-04-18 23:52:55     return self._request(
2024-04-18 23:52:55            ^^^^^^^^^^^^^^
2024-04-18 23:52:55   File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 542, in _request
2024-04-18 23:52:55     self._handle_error_responses(data, params, response)
2024-04-18 23:52:55   File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 786, in _handle_error_responses
2024-04-18 23:52:55     raise UnsupportedMediaType415Error(response.text)
2024-04-18 23:52:55 qbittorrentapi.exceptions.UnsupportedMediaType415Error: 错误：'torrent__4' 不是一个有效的 torrent 文件。
2024-04-18 23:54:53 [2024-04-18 23:54:53] INFO:     [ANi] 為美好的世界獻上祝福！3 - 02 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4 >> 為美好的世界獻上祝福！3 S01E02.mp4
```

**Comment by jiangshuai341** [comment]
24-04-19 00:06:40 groupmod: invalid group ID '$(id -g)'
2024-04-19 00:06:40 usermod: invalid user ID '$(id -u)'
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:     Started server process [7]
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:     Waiting for application startup.
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:     
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:                     _        ____                                    _
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:          /\        | |      |  _ \                                  (_)
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:                                                 __/ |
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:                                                |___/
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:     Version 3.1.13  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:     Starting AutoBangumi...
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:     Config loaded
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:     Program running.
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:     Application startup complete.
2024-04-19 00:06:41 [2024-04-19 00:06:41] INFO:     Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
2024-04-19 00:06:43 [2024-04-19 00:06:43] INFO:     Start collecting full season...
2024-04-19 00:06:43 [2024-04-19 00:06:43] INFO:     Start collecting 关于我转生变成史莱姆这档事 Season 3...
2024-04-19 00:06:46 Exception in thread Thread-4 (rss_loop):
2024-04-19 00:06:46 Traceback (most recent call last):
2024-04-19 00:06:46   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
2024-04-19 00:06:46     self.run()
2024-04-19 00:06:46   File "/usr/lib/python3.11/threading.py", line 982, in run
2024-04-19 00:06:46     self._target(*self._args, **self._kwargs)
2024-04-19 00:06:46   File "/app/module/core/sub_thread.py", line 31, in rss_loop
2024-04-19 00:06:46     eps_complete()
2024-04-19 00:06:46   File "/app/module/manager/collector.py", line 72, in eps_complete
2024-04-19 00:06:46     collector.collect_season(data)
2024-04-19 00:06:46   File "/app/module/manager/collector.py", line 21, in collect_season
2024-04-19 00:06:46     if self.add_torrent(torrents, bangumi):
2024-04-19 00:06:46        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-19 00:06:46   File "/app/module/downloader/download_client.py", line 138, in add_torrent
2024-04-19 00:06:46     if self.client.add_torrents(
2024-04-19 00:06:46        ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-19 00:06:46   File "/app/module/downloader/client/qb_downloader.py", line 86, in add_torrents
2024-04-19 00:06:46     resp = self._client.torrents_add(
2024-04-19 00:06:46            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-19 00:06:46   File "/usr/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 91, in wrapper
2024-04-19 00:06:46     return func(client, *args, **kwargs)
2024-04-19 00:06:46            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-19 00:06:46   File "/usr/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 1306, in torrents_add
2024-04-19 00:06:46     return self._post(
2024-04-19 00:06:46            ^^^^^^^^^^^
2024-04-19 00:06:46   File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 390, in _post
2024-04-19 00:06:46     return self._request_manager(
2024-04-19 00:06:46            ^^^^^^^^^^^^^^^^^^^^^^
2024-04-19 00:06:46   File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 465, in _request_manager
2024-04-19 00:06:46     return self._request(
2024-04-19 00:06:46            ^^^^^^^^^^^^^^
2024-04-19 00:06:46   File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 542, in _request
2024-04-19 00:06:46     self._handle_error_responses(data, params, response)
2024-04-19 00:06:46   File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 786, in _handle_error_responses
2024-04-19 00:06:46     raise UnsupportedMediaType415Error(response.text)
2024-04-19 00:06:46 qbittorrentapi.exceptions.UnsupportedMediaType415Error: 错误：'torrent__4' 不是一个有效的 torrent 文件。
2024-04-19 00:07:39 [2024-04-19 00:07:39] INFO:     Config loaded
2024-04-19 00:07:39 [2024-04-19 00:07:39] INFO:     Config updated
2024-04-19 00:07:39 [2024-04-19 00:07:39] INFO:     Config loaded
2024-04-19 00:07:39 [2024-04-19 00:07:39] INFO:     Program running.
2024-04-19 00:07:40 [2024-04-19 00:07:40] INFO:     Start collecting full season...
2024-04-19 00:07:40 [2024-04-19 00:07:40] INFO:     Start collecting 关于我转生变成史莱姆这档事 Season 3...
2024-04-19 00:07:41 Exception in thread Thread-6 (rss_loop):
2024-04-19 00:07:41 Traceback (most recent call last):
2024-04-19 00:07:41   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
2024-04-19 00:07:41     self.run()
2024-04-19 00:07:41   File "/usr/lib/python3.11/threading.py", line 982, in run
2024-04-19 00:07:41     self._target(*self._args, **self._kwargs)
2024-04-19 00:07:41   File "/app/module/core/sub_thread.py", line 31, in rss_loop
2024-04-19 00:07:41     eps_complete()
2024-04-19 00:07:41   File "/app/module/manager/collector.py", line 72, in eps_complete
2024-04-19 00:07:41     collector.collect_season(data)
2024-04-19 00:07:41   File "/app/module/manager/collector.py", line 21, in collect_season
2024-04-19 00:07:41     if self.add_torrent(torrents, bangumi):
2024-04-19 00:07:41        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-19 00:07:41   File "/app/module/downloader/download_client.py", line 138, in add_torrent
2024-04-19 00:07:41     if self.client.add_torrents(
2024-04-19 00:07:41        ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-19 00:07:41   File "/app/module/downloader/client/qb_downloader.py", line 86, in add_torrents
2024-04-19 00:07:41     resp = self._client.torrents_add(
2024-04-19 00:07:41            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-19 00:07:41   File "/usr/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 91, in wrapper
2024-04-19 00:07:41     return func(client, *args, **kwargs)
2024-04-19 00:07:41            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-19 00:07:41   File "/usr/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 1306, in torrents_add
2024-04-19 00:07:41     return self._post(
2024-04-19 00:07:41            ^^^^^^^^^^^
2024-04-19 00:07:41   File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 390, in _post
2024-04-19 00:07:41     return self._request_manager(
2024-04-19 00:07:41            ^^^^^^^^^^^^^^^^^^^^^^
2024-04-19 00:07:41   File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 465, in _request_manager
2024-04-19 00:07:41     return self._request(
2024-04-19 00:07:41            ^^^^^^^^^^^^^^
2024-04-19 00:07:41   File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 542, in _request
2024-04-19 00:07:41     self._handle_error_responses(data, params, response)
2024-04-19 00:07:41   File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 786, in _handle_error_responses
2024-04-19 00:07:41     raise UnsupportedMediaType415Error(response.text)
2024-04-19 00:07:41 qbittorrentapi.exceptions.UnsupportedMediaType415Error: 错误：'torrent__4' 不是一个有效的 torrent 文件。

**Comment by jiangshuai341** [comment]
更新到最新13版本还是有报错

**Comment by manipEgo** [comment]
遇见相同问题，只有特定订阅会导致这个问题。我的情况是在补全 2024 春季，芝士动物朋友组发布的 DDDD 恶魔的破坏时产生错误，供复现。
