### ISSUE TITLE
获取不了新种子，且日志不匹配

### ISSUE THREAD

**Issue by frankh1111** [EstrellaXD/Auto_Bangumi#755]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.13

### 问题类型

程序运行问题

### 问题描述

自4.29起 程序在多次重启、等待后，均获取不了新种子，并且日志显示正常，而在程序的log上却能看到问题日志

### 发生问题时系统日志

```bash
DEBUG:    [Renamer] Start rename process.
DEBUG:    [Renamer] Rename process finished.
DEBUG:    [Network] Successfully connected to https://mikanime.tv/RSS/MyBangumi?token=Q4N1yNVG5%2bDx2yw2ebt5mA%3d%3d. Status: 200
Exception in thread Thread-4 (rss_loop):
Traceback (most recent call last):
File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
self.run()
File "/usr/lib/python3.11/threading.py", line 982, in run
self._target(*self._args, **self._kwargs)
File "/app/module/core/sub_thread.py", line 27, in rss_loop
self.analyser.rss_to_data(rss, engine)
File "/app/module/rss/analyser.py", line 69, in rss_to_data
rss_torrents = self.get_rss_torrents(rss.url, full_parse)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/rss/analyser.py", line 40, in get_rss_torrents
rss_torrents = req.get_torrents(rss_link)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/network/request_contents.py", line 29, in get_torrents
if re.search(_filter, _title) is None:
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/re/__init__.py", line 176, in search
return _compile(pattern, flags).search(string)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
p = _compiler.compile(pattern, flags)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/re/_compiler.py", line 745, in compile
p = _parser.parse(p, flags)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/re/_parser.py", line 989, in parse
p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/re/_parser.py", line 464, in _parse_sub
itemsappend(_parse(source, state, verbose, nested + 1,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/re/_parser.py", line 691, in _parse
raise source.error("nothing to repeat",
re.error: nothing to repeat at position 42
```

**Comment by frankh1111** [comment]
不过这是发生我的truenas scale中，并且使用的是k3s
