### ISSUE TITLE
[错误报告] RSS没有正常工作

### ISSUE THREAD

**Issue by rong-xiaoli** [EstrellaXD/Auto_Bangumi#761]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.13（docker）

### 问题类型

程序运行问题

### 问题描述

日志提示无法获取某张图片（原因是网络环境不支持，挂了梯子也一样，貌似是mikan的问题）然后就没有任何动作了（个人猜测是RSS订阅循环异常退出了）
可以试着单独拎出循环传错误参数试试看？

### 发生问题时系统日志

```bash
2024-05-02 15:06:13.011610+08:00TypeError: object supporting the buffer API required
2024-05-02 15:10:48.781693+08:00[2024-05-02 15:10:48] INFO:     Config loaded
2024-05-02 15:10:48.782042+08:00[2024-05-02 15:10:48] INFO:     Config updated
2024-05-02 15:10:48.795226+08:00[2024-05-02 15:10:48] INFO:     Config loaded
2024-05-02 15:10:48.805320+08:00[2024-05-02 15:10:48] INFO:     Program running.
2024-05-02 15:11:06.796299+08:00[2024-05-02 15:11:06] ERROR     [Network] Unable to connect to https://mikanani.hacgn.fun/images/Bangumi/202401/d823efac.jpg, Please check your network settings
2024-05-02 15:11:06.809368+08:00Exception in thread Thread-20 (rss_loop):
2024-05-02 15:11:06.809596+08:00Traceback (most recent call last):
2024-05-02 15:11:06.809664+08:00File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
2024-05-02 15:11:06.809758+08:00self.run()
2024-05-02 15:11:06.809858+08:00File "/usr/lib/python3.11/threading.py", line 982, in run
2024-05-02 15:11:06.810876+08:00self._target(*self._args, **self._kwargs)
2024-05-02 15:11:06.811054+08:00File "/app/module/core/sub_thread.py", line 27, in rss_loop
2024-05-02 15:11:06.811473+08:00self.analyser.rss_to_data(rss, engine)
2024-05-02 15:11:06.811595+08:00File "/app/module/rss/analyser.py", line 75, in rss_to_data
2024-05-02 15:11:06.811989+08:00new_data = self.torrents_to_data(torrents_to_add, rss, full_parse)
2024-05-02 15:11:06.812193+08:00^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-02 15:11:06.812302+08:00File "/app/module/rss/analyser.py", line 52, in torrents_to_data
2024-05-02 15:11:06.812946+08:00self.official_title_parser(bangumi=bangumi, rss=rss, torrent=torrent)
2024-05-02 15:11:06.813185+08:00File "/app/module/rss/analyser.py", line 18, in official_title_parser
2024-05-02 15:11:06.813637+08:00bangumi.poster_link, bangumi.official_title = self.mikan_parser(
2024-05-02 15:11:06.816432+08:00^^^^^^^^^^^^^^^^^^
2024-05-02 15:11:06.816668+08:00File "/app/module/parser/title_parser.py", line 108, in mikan_parser
2024-05-02 15:11:06.816718+08:00return mikan_parser(homepage)
2024-05-02 15:11:06.816759+08:00^^^^^^^^^^^^^^^^^^^^^^
2024-05-02 15:11:06.816799+08:00File "/app/module/parser/analyser/mikan_parser.py", line 25, in mikan_parser
2024-05-02 15:11:06.816839+08:00poster_link = save_image(img, suffix)
2024-05-02 15:11:06.816905+08:00^^^^^^^^^^^^^^^^^^^^^^^
2024-05-02 15:11:06.816946+08:00File "/app/module/utils/cache_image.py", line 5, in save_image
2024-05-02 15:11:06.816987+08:00img_hash = hashlib.md5(img).hexdigest()[0:8]
2024-05-02 15:11:06.817161+08:00^^^^^^^^^^^^^^^^
2024-05-02 15:11:06.817267+08:00TypeError: object supporting the buffer API required
```
```

**Comment by rong-xiaoli** [comment]
嗯，不知道为什么，搞定了？这玩意儿我换了个订阅域名，能跑。
我就不动它了，再过几天，没问题了就close

**Comment by rong-xiaoli** [comment]
看起来确实是订阅链接的问题，close了，不好意思误报了
