### ISSUE TITLE
[错误报告]为啥girls band cry订阅了却识别不到呢？

### ISSUE THREAD

**Issue by crazyhonor** [EstrellaXD/Auto_Bangumi#770]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.13

### 问题类型

其他问题

### 问题描述

明明订阅了girls band cry，却识别不到这个订阅，其他番剧都是能订阅到的，很奇怪。系统是unraid，docker部署，之前在群晖上是能够识别到的，不知道是哪里出了问题。

### 发生问题时系统日志

```bash
[2024-05-18 21:26:25]
INFO
Version 3.1.13 Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2024-05-18 21:26:25]
INFO
GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2024-05-18 21:26:25]
INFO
Starting AutoBangumi...
[2024-05-18 21:26:25]
INFO
Config loaded
[2024-05-18 21:26:25]
INFO
Program running.
[2024-05-18 21:26:25]
INFO
Application startup complete.
[2024-05-18 21:26:25]
INFO
Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
[2024-05-18 21:26:29]
INFO
Start collecting full season...
[2024-05-18 21:26:29]
INFO
Start collecting 喂！蜻蜓 Season 1...
[2024-05-18 21:26:31]
WARNING
Already collected 喂！蜻蜓 Season 1.
[2024-05-18 21:26:31]
INFO
Start collecting 极速星舞 Season 1...
[2024-05-18 21:26:32]
WARNING
Already collected 极速星舞 Season 1.
[2024-05-18 21:26:33]
INFO
Start collecting 末班列车去哪里了？ Season 1...
[2024-05-18 21:26:34]
WARNING
Already collected 末班列车去哪里了？ Season 1.
[2024-05-18 21:26:34]
INFO
Start collecting 关于我转生变成史莱姆这档事 Season 3...
[2024-05-18 21:32:30]
INFO
[ANi] 蜻蛉高球 - 07 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4 >> 喂！蜻蜓 S01E07.mp4
[2024-05-18 21:33:37]
INFO
[ANi] 蜻蛉高球 - 04 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4 >> 喂！蜻蜓 S01E04.mp4
[2024-05-18 22:13:48]
INFO
Config loaded
[2024-05-18 22:13:48]
INFO
Program running.
[2024-05-18 22:13:51]
INFO
[RSS] New bangumi founded: 极速星舞
[2024-05-18 22:13:52]
INFO
[RSS] New bangumi founded: 末班列车去哪里了？
[2024-05-18 22:13:53]
INFO
[RSS] New bangumi founded: 关于我转生变成史莱姆这档事
[2024-05-18 22:13:58]
INFO
[RSS] New bangumi founded: 星际庄的恋爱日记
[2024-05-18 22:14:02]
INFO
[RSS] New bangumi founded: 无名记忆
[2024-05-18 22:14:04]
INFO
[RSS] New bangumi founded: 怪人的沙拉碗
[2024-05-18 22:14:05]
INFO
[RSS] New bangumi founded: 防风少年
[2024-05-18 22:14:06]
INFO
[RSS] New bangumi founded: 身为魔王的我娶了奴隶精灵为妻，该如何表白我的爱？
[2024-05-18 22:14:09]
INFO
[RSS] New bangumi founded: 怪异与少女与神隐
[2024-05-18 22:14:10]
INFO
[RSS] New bangumi founded: 摇曳露营△
[2024-05-18 22:14:12]
INFO
[RSS] New bangumi founded: 格斗实况
[2024-05-18 22:14:13]
INFO
[RSS] New bangumi founded: 调酒师 神之杯
[2024-05-18 22:14:15]
INFO
[RSS] New bangumi founded: 约会大作战
[2024-05-18 22:14:17]
INFO
[RSS] New bangumi founded: 为美好的世界献上祝福！
[2024-05-18 22:14:19]
INFO
[RSS] New bangumi founded: 声优广播的台前幕后
[2024-05-18 22:14:21]
INFO
[RSS] New bangumi founded: 单间、光照尚好、附带天使。
[2024-05-18 22:14:22]
INFO
[RSS] New bangumi founded: 怪物转生
[2024-05-18 22:14:24]
INFO
[RSS] New bangumi founded: 从Lv2开始开挂的原勇者候补悠闲的异世界生活
[2024-05-18 22:14:25]
INFO
[RSS] New bangumi founded: 神渴望着游戏。
[2024-05-18 22:14:27]
INFO
[RSS] New bangumi founded: 杀手寓言
[2024-05-18 22:14:28]
INFO
[RSS] New bangumi founded: 蔚蓝档案 动画版
[2024-05-18 22:14:29]
INFO
[RSS] New bangumi founded: 无职转生Ⅱ ～到了异世界就拿出真本事～ 第2部分
[2024-05-18 22:14:31]
INFO
[RSS] New bangumi founded: 爷爷奶奶返老还童
[2024-05-18 22:14:32]
INFO
[RSS] New bangumi founded: 死神少爷与黑女仆
[2024-05-18 22:14:34]
INFO
[RSS] New bangumi founded: 吹响！悠风号
[2024-05-18 22:14:38]
INFO
[RSS] New bangumi founded: 夜樱家的大作战
[2024-05-18 22:14:40]
INFO
[RSS] New bangumi founded: 夜晚的水母不会游泳
[2024-05-18 22:14:42]
INFO
[RSS] New bangumi founded: 怪兽8号
[2024-05-18 22:14:43]
INFO
[RSS] New bangumi founded: 迷宫饭
[2024-05-18 22:14:46]
INFO
Start collecting full season...
[2024-05-18 22:14:46]
INFO
Start collecting 极速星舞 Season 1...
[2024-05-18 22:14:51]
WARNING
Already collected 极速星舞 Season 1.
[2024-05-18 22:14:51]
INFO
Start collecting 末班列车去哪里了？ Season 1...
[2024-05-18 22:14:53]
WARNING
Already collected 末班列车去哪里了？ Season 1.
[2024-05-18 22:14:53]
INFO
Start collecting 关于我转生变成史莱姆这档事 Season 3...
[2024-05-18 22:16:50]
INFO
[ANi] 怪獸 8 號 - 05 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4 >> 怪兽8号 S01E05.mp4
```

**Comment by crazyhonor** [comment]
Exception in thread Thread-10 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 31, in rss_loop
    eps_complete()
  File "/app/module/manager/collector.py", line 72, in eps_complete
    collector.collect_season(data)
  File "/app/module/manager/collector.py", line 21, in collect_season
    if self.add_torrent(torrents, bangumi):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/downloader/download_client.py", line 138, in add_torrent
    if self.client.add_torrents(
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/downloader/client/qb_downloader.py", line 86, in add_torrents
    resp = self._client.torrents_add(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 91, in wrapper
    return func(client, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 1306, in torrents_add
    return self._post(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 390, in _post
    return self._request_manager(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 465, in _request_manager
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 542, in _request
    self._handle_error_responses(data, params, response)
  File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 786, in _handle_error_responses
    raise UnsupportedMediaType415Error(response.text)
qbittorrentapi.exceptions.UnsupportedMediaType415Error: 错误：'torrent__9' 不是一个有效的 torrent 文件。
