### ISSUE TITLE
[错误报告]在mikan中添加 ani 关于我转生变成史莱姆这档事s3 的时候会提示 服务器错误！

### ISSUE THREAD

**Issue by Magic-riding** [EstrellaXD/Auto_Bangumi#774]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

Version: 3.1.13

### 问题类型

程序运行问题

### 问题描述

在mikan中添加 ani 关于我转生变成史莱姆这档事s3 的时候会提示 服务器错误！在rss中会显示已经添加，在主页面无法显示，在qb中只会添加一个 ani 关于我转生变成史莱姆这档事s3e54 的种子，无法添加其他种子

### 发生问题时系统日志

```bash
[2024-05-26 19:13:18]
ERROR
ERROR Exception in ASGI application
Traceback (most recent call last)
File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
result = await app( # type ignore[func-returns-value]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
return await self.app(scope, receive, send)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
raise exc from None
File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
await self.app(scope, inner_receive, inner_send)
File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
await super().__call__(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
await self.middleware_stack(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
raise exc
File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
await self.app(scope, receive, _send)
File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
raise exc
File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
await self.app(scope, receive, sender)
File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
raise e
File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
await self.app(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
await route.handle(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
await self.app(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
response = await func(request)
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
raw_response = await run_endpoint_function(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
return await dependant.call(**values)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/api/rss.py", line 199, in subscribe
resp = collector.subscribe_season(data, parser=rss.parser)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/manager/collector.py", line 59, in subscribe_season
result = engine.download_bangumi(data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/rss/engine.py", line 141, in download_bangumi
client.add_torrent(torrents, bangumi)
File "/app/module/downloader/download_client.py", line 138, in add_torrent
if self.client.add_torrents(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/downloader/client/qb_downloader.py", line 86, in add_torrents
resp = self._client.torrents_add(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 91, in wrapper
return func(client, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 1306, in torrents_add
return self._post(
^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 390, in _post
return self._request_manager(
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 465, in _request_manager
return self._request(
^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 542, in _request
self._handle_error_responses(data, params, response)
File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 786, in _handle_error_responses
raise UnsupportedMediaType415Error(response.text)
qbittorrentapi.exceptions.UnsupportedMediaType415Error 错误：'torrent__10' 不是一个有效的 torrent 文件。
```

**Comment by 1983shake** [comment]
我昨天用docker架起了服务，在订阅RSS的时候，也是出现服务器错误，出现了“ERROR Exception in ASGI application”。实际原因是因为订阅里的种子，有坏的，所及AB订阅时会出错，导致服务器错误。需要作者看如何处理。谢谢。
如下图我使用迅雷去解析链接种子，都是未知的，就是该种子导致的，过滤掉该种子的链接，就能AB正常订阅了。
![企业微信截图_20240628121400](https://github.com/EstrellaXD/Auto_Bangumi/assets/40011475/af078cf4-d4ee-4033-9c90-3b6212eb7ffd)

**Comment by 1983shake** [comment]
我昨天用docker架起了服务，在订阅RSS的时候，也是出现服务器错误，出现了“ERROR Exception in ASGI application”。实际原因是因为订阅里的种子，有坏的，所及AB订阅时会出错，导致服务器错误。需要作者看如何处理。谢谢。
如下图我使用迅雷去解析链接种子，都是未知的，就是该种子导致的，过滤掉该种子的链接，就能AB正常订阅了。
![企业微信截图_20240628121400](https://github.com/EstrellaXD/Auto_Bangumi/assets/40011475/af078cf4-d4ee-4033-9c90-3b6212eb7ffd)

**Comment by Spectre-2022** [comment]
俺也一样
INFO
[2024-07-04 00:50:53]
Version 3.1.14 Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
INFO
[2024-07-04 00:50:53]
GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
INFO
[2024-07-04 00:50:53]
Starting AutoBangumi...
INFO
[2024-07-04 00:50:53]
Config loaded
INFO
[2024-07-04 00:50:54]
Program running.
INFO
[2024-07-04 00:50:54]
Application startup complete.
INFO
[2024-07-04 00:50:54]
Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
ERROR
[2024-07-04 00:51:40]
ERROR Exception in ASGI application
Traceback (most recent call last)
File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
result = await app( # type ignore[func-returns-value]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
return await self.app(scope, receive, send)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
raise exc from None
File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
await self.app(scope, inner_receive, inner_send)
File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
await super().__call__(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
await self.middleware_stack(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
raise exc
File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
await self.app(scope, receive, _send)
File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
raise exc
File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
await self.app(scope, receive, sender)
File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
raise e
File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
await self.app(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
await route.handle(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
await self.app(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
response = await func(request)
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
raw_response = await run_endpoint_function(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
return await dependant.call(**values)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/api/rss.py", line 199, in subscribe
resp = collector.subscribe_season(data, parser=rss.parser)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/manager/collector.py", line 59, in subscribe_season
result = engine.download_bangumi(data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/rss/engine.py", line 141, in download_bangumi
client.add_torrent(torrents, bangumi)
File "/app/module/downloader/download_client.py", line 138, in add_torrent
if self.client.add_torrents(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/downloader/client/qb_downloader.py", line 86, in add_torrents
resp = self._client.torrents_add(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 91, in wrapper
return func(client, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 1306, in torrents_add
return self._post(
^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 390, in _post
return self._request_manager(
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 465, in _request_manager
return self._request(
^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 542, in _request
self._handle_error_responses(data, params, response)
File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 786, in _handle_error_responses
raise UnsupportedMediaType415Error(response.text)
qbittorrentapi.exceptions.UnsupportedMediaType415Error 错误：'torrent__15' 不是一个有效的 torrent 文件。
ERROR
[2024-07-04 00:55:33]
ERROR Exception in ASGI application
Traceback (most recent call last)
File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
result = await app( # type ignore[func-returns-value]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
return await self.app(scope, receive, send)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
raise exc from None
File "/usr/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
await self.app(scope, inner_receive, inner_send)
File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
await super().__call__(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
await self.middleware_stack(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
raise exc
File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
await self.app(scope, receive, _send)
File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
raise exc
File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
await self.app(scope, receive, sender)
File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
raise e
File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
await self.app(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
await route.handle(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
await self.app(scope, receive, send)
File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
response = await func(request)
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
raw_response = await run_endpoint_function(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
return await dependant.call(**values)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/api/rss.py", line 199, in subscribe
resp = collector.subscribe_season(data, parser=rss.parser)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/manager/collector.py", line 59, in subscribe_season
result = engine.download_bangumi(data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/rss/engine.py", line 141, in download_bangumi
client.add_torrent(torrents, bangumi)
File "/app/module/downloader/download_client.py", line 138, in add_torrent
if self.client.add_torrents(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/module/downloader/client/qb_downloader.py", line 86, in add_torrents
resp = self._client.torrents_add(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/decorators.py", line 91, in wrapper
return func(client, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/torrents.py", line 1306, in torrents_add
return self._post(
^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 390, in _post
return self._request_manager(
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 465, in _request_manager
return self._request(
^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 542, in _request
self._handle_error_responses(data, params, response)
File "/usr/lib/python3.11/site-packages/qbittorrentapi/request.py", line 786, in _handle_error_responses
raise UnsupportedMediaType415Error(response.text)
qbittorrentapi.exceptions.UnsupportedMediaType415Error 错误：'torrent__15' 不是一个有效的 torrent 文件。
