### ISSUE TITLE
[错误报告]程序运行一段时间后不会自动下载rss订阅更新的番剧

### ISSUE THREAD

**Issue by finalpi** [EstrellaXD/Auto_Bangumi#785]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.14

### 问题类型

程序运行问题

### 问题描述

如题,自从2024-06-06这个时间之后订阅更新的番剧没有自动下载,解决方法是重启程序,然后会一次性下载这期间没有下载过的所有番剧

### 发生问题时系统日志

```bash
ab  | [2024-06-05 15:28:19] ERROR     [Network] Unable to connect to https://mikanani.me/RSS/Search?searchstr=星空字幕组+Boku+no+Kokoro+no+Yabai+Yatsu+简日双语+1080P, Please check your network settings
ab  | --- Logging error ---
ab  | Traceback (most recent call last):
ab  |   File "/usr/lib/python3.11/logging/__init__.py", line 1114, in emit
ab  |     self.flush()
ab  |   File "/usr/lib/python3.11/logging/__init__.py", line 1094, in flush
ab  |     self.stream.flush()
ab  | OSError: [Errno 28] No space left on device
ab  | Call stack:
ab  |   File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
ab  |     self._bootstrap_inner()
ab  |   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
ab  |     self.run()
ab  |   File "/usr/lib/python3.11/threading.py", line 982, in run
ab  |     self._target(*self._args, **self._kwargs)
ab  |   File "/app/module/core/sub_thread.py", line 29, in rss_loop
ab  |     engine.refresh_rss(client)
ab  |   File "/app/module/rss/engine.py", line 123, in refresh_rss
ab  |     new_torrents = self.pull_rss(rss_item)
ab  |   File "/app/module/rss/engine.py", line 98, in pull_rss
ab  |     torrents = self._get_torrents(rss_item)
ab  |   File "/app/module/rss/engine.py", line 21, in _get_torrents
ab  |     torrents = req.get_torrents(rss.url)
ab  |   File "/app/module/network/request_contents.py", line 38, in get_torrents
ab  |     logger.warning(f"[Network] Failed to get torrents: {_url}")
ab  | Message: '[Network] Failed to get torrents: https://mikanani.me/RSS/Search?searchstr=星空字幕组+Boku+no+Kokoro+no+Yabai+Yatsu+简日双语+1080P'
ab  | Arguments: ()
ab  | [2024-06-05 15:28:19] WARNING:  [Network] Failed to get torrents: https://mikanani.me/RSS/Search?searchstr=星空字幕组+Boku+no+Kokoro+no+Yabai+Yatsu+简日双语+1080P
ab  | Exception in thread Thread-4 (rss_loop):
ab  | Traceback (most recent call last):
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
ab  |     self.dialect.do_execute(
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
ab  |     cursor.execute(statement, parameters)
ab  | sqlite3.OperationalError: database or disk is full
ab  | 
ab  | The above exception was the direct cause of the following exception:
ab  | 
ab  | Traceback (most recent call last):
ab  |   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
ab  |     self.run()
ab  |   File "/usr/lib/python3.11/threading.py", line 982, in run
ab  |     self._target(*self._args, **self._kwargs)
ab  |   File "/app/module/core/sub_thread.py", line 29, in rss_loop
ab  |     engine.refresh_rss(client)
ab  |   File "/app/module/rss/engine.py", line 132, in refresh_rss
ab  |     self.torrent.add_all(new_torrents)
ab  |   File "/app/module/database/torrent.py", line 22, in add_all
ab  |     self.session.commit()
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
ab  |     self._transaction.commit(_to_root=self.future)
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 829, in commit
ab  |     self._prepare_impl()
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
ab  |     self.session.flush()
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
ab  |     self._flush(objects)
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3525, in _flush
ab  |     with util.safe_reraise():
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
ab  |     compat.raise_(
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
ab  |     raise exception
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
ab  |     flush_context.execute()
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
ab  |     rec.execute(self)
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
ab  |     util.preloaded.orm_persistence.save_obj(
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
ab  |     _emit_insert_statements(
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
ab  |     result = connection._execute_20(
ab  |              ^^^^^^^^^^^^^^^^^^^^^^^
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
ab  |     return meth(self, args_10style, kwargs_10style, execution_options)
ab  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
ab  |     return connection._execute_clauseelement(
ab  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
ab  |     ret = self._execute_context(
ab  |           ^^^^^^^^^^^^^^^^^^^^^^
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
ab  |     self._handle_dbapi_exception(
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
ab  |     util.raise_(
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
ab  |     raise exception
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
ab  |     self.dialect.do_execute(
ab  |   File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
ab  |     cursor.execute(statement, parameters)
ab  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database or disk is full
ab  | [SQL: INSERT INTO torrent (bangumi_id, rss_id, name, url, homepage, downloaded) VALUES (?, ?, ?, ?, ?, ?)]
ab  | [parameters: (26, 1, '【喵萌奶茶屋】★04月新番★[夜晚的水母不会游泳 / Yoru no Kurage wa Oyogenai][09][1080p][简日双语][招募翻译时轴]', 'https://mikanani.me/Download/20240605/2ec0a6beae2b9474628826bc79fb393a54286854.torrent', 'https://mikanani.me/Home/Episode/2ec0a6beae2b9474628826bc79fb393a54286854', 1)]
ab  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
ab  | --- Logging error ---
ab  | Traceback (most recent call last):
ab  |   File "/usr/lib/python3.11/logging/__init__.py", line 1114, in emit
ab  |     self.flush()
ab  |   File "/usr/lib/python3.11/logging/__init__.py", line 1094, in flush
ab  |     self.stream.flush()
ab  | OSError: [Errno 28] No space left on device
ab  | Call stack:
ab  |   File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
ab  |     self._bootstrap_inner()
ab  |   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
ab  |     self.run()
ab  |   File "/usr/lib/python3.11/threading.py", line 982, in run
ab  |     self._target(*self._args, **self._kwargs)
ab  |   File "/app/module/core/sub_thread.py", line 60, in rename_loop
ab  |     renamed_info = renamer.rename()
ab  |   File "/app/module/manager/renamer.py", line 157, in rename
ab  |     notify_info = self.rename_file(media_path=media_list[0], **kwargs)
ab  |   File "/app/module/manager/renamer.py", line 70, in rename_file
ab  |     if self.rename_torrent_file(
ab  |   File "/app/module/downloader/download_client.py", line 108, in rename_torrent_file
ab  |     logger.info(f"{old_path} >> {new_path}")
ab  | Message: '[Nekomoe kissaten][Yoru no Kurage wa Oyogenai][09][1080p][JPSC].mp4 >> 夜晚的水母不会游泳 S01E09.mp4'
ab  | Arguments: ()
ab  | [2024-06-06 01:30:41] INFO:     [Nekomoe kissaten][Yoru no Kurage wa Oyogenai][09][1080p][JPSC].mp4 >> 夜晚的水母不会游泳 S01E09.mp4
```

**Comment by cxwsssj** [comment]
我遇到了同样的问题，docker版本，请问楼主问题解决了吗？

**Comment by aicon2333** [comment]
一样的问题

**Comment by shininome** [comment]
已经解决(大概

**Comment by finalpi** [comment]
重启docker镜像之后,截止目前很长时间没有复现这个问题了

**Comment by cxwsssj** [comment]
> 重启docker镜像之后,截止目前很长时间没有复现这个问题了

我尝试了重启docker镜像，依然存在这个问题。
