### ISSUE TITLE
xml解析错误

### ISSUE THREAD

**Issue by jiaxinonly** [EstrellaXD/Auto_Bangumi#788]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.14

### 问题类型

程序运行问题

### 问题描述

似乎番剧补全解析xml出现了问题，我添加了mikanime.tv订阅，然后日志提示去mikanime.tv查找失败，然后修改了search_provider.json文件里面的地址，重启后似乎恢复了正常（不太确定，但是目录里面下载了22和23集），然后本身之前手动下载了无职转生前一半，为了让文件夹保持一致，将默认的`无职转生Ⅱ ～到了异世界就拿出真本事～ 第2部分`修改为`无职转生 ～到了异世界就拿出真本事～`后无法再继续下载前面的剧集，即使改回去也一样，docker日志里面显示xml解析错误

### 发生问题时系统日志

```bash
[2024-06-25 21:46:59] INFO:     Started server process [6]
[2024-06-25 21:46:59] INFO:     Waiting for application startup.
[2024-06-25 21:46:59] INFO:     
[2024-06-25 21:46:59] INFO:                     _        ____                                    _
[2024-06-25 21:46:59] INFO:          /\        | |      |  _ \                                  (_)
[2024-06-25 21:46:59] INFO:         /  \  _   _| |_ ___ | |_) | __ _ _ __   __ _ _   _ _ __ ___  _
[2024-06-25 21:46:59] INFO:        / /\ \| | | | __/ _ \|  _ < / _` | '_ \ / _` | | | | '_ ` _ \| |
[2024-06-25 21:46:59] INFO:       / ____ \ |_| | || (_) | |_) | (_| | | | | (_| | |_| | | | | | | |
[2024-06-25 21:46:59] INFO:      /_/    \_\__,_|\__\___/|____/ \__,_|_| |_|\__, |\__,_|_| |_| |_|_|
[2024-06-25 21:46:59] INFO:                                                 __/ |
[2024-06-25 21:46:59] INFO:                                                |___/
[2024-06-25 21:46:59] INFO:     Version 3.1.14  Author: EstrellaXD Twitter: https://twitter.com/Estrella_Pan
[2024-06-25 21:46:59] INFO:     GitHub: https://github.com/EstrellaXD/Auto_Bangumi/
[2024-06-25 21:46:59] INFO:     Starting AutoBangumi...
/app/module/database/bangumi.py:28: SAWarning: Identity map already had an identity for (<class 'module.models.bangumi.Bangumi'>, (4,), None), replacing it with newly flushed object.   Are there load operations occurring inside of an event handler within the flush?
  self.session.commit()
[2024-06-25 21:47:09] ERROR     [Network] Unable to connect to , Please check your network settings
[2024-06-25 21:47:09] INFO:     [Core] Database updated.
[2024-06-25 21:47:09] INFO:     Config loaded
[2024-06-25 21:47:09] INFO:     Program running.
[2024-06-25 21:47:09] INFO:     Application startup complete.
[2024-06-25 21:47:09] INFO:     Uvicorn running on http://0.0.0.0:7892 (Press CTRL+C to quit)
[2024-06-25 21:51:19] INFO:     Config loaded
[2024-06-25 21:51:19] INFO:     Config updated
[2024-06-25 21:51:19] INFO:     Config loaded
[2024-06-25 21:51:19] INFO:     Program running.
[2024-06-25 21:51:31] INFO:     [Manager] Delete rule for 迷宫饭
[2024-06-25 21:51:34] INFO:     [Manager] Delete rule for 关于我转生变成史莱姆这档事
[2024-06-25 21:51:37] INFO:     [Manager] Delete rule for 吹响！悠风号
[2024-06-25 21:51:41] INFO:     [Manager] Delete rule for 无职转生 ～到了异世界就拿出真本事～
[2024-06-25 21:52:19] INFO:     Config loaded
[2024-06-25 21:52:19] INFO:     Program running.
[2024-06-25 21:52:21] INFO:     [RSS] New bangumi founded: 无职转生Ⅱ ～到了异世界就拿出真本事～ 第2部分
[2024-06-25 21:52:23] INFO:     [RSS] New bangumi founded: 吹响！悠风号
[2024-06-25 21:52:24] INFO:     [RSS] New bangumi founded: 关于我转生变成史莱姆这档事
[2024-06-25 21:52:26] INFO:     [RSS] New bangumi founded: 迷宫饭
[2024-06-25 21:52:31] INFO:     Start collecting full season...
[2024-06-25 21:52:31] INFO:     Start collecting 无职转生Ⅱ ～到了异世界就拿出真本事～ 第2部分 Season 2...
Exception in thread Thread-8 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 31, in rss_loop
    eps_complete()
  File "/app/module/manager/collector.py", line 72, in eps_complete
    collector.collect_season(data)
  File "/app/module/manager/collector.py", line 18, in collect_season
    torrents = st.search_season(bangumi)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 54, in search_season
    torrents = self.search_torrents(rss_item)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 24, in search_torrents
    return self.get_torrents(rss_item.url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 22, in get_torrents
    soup = self.get_xml(_url, retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 44, in get_xml
    return xml.etree.ElementTree.fromstring(req.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1345, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
[2024-06-25 21:53:19] INFO:     [ANi] 關於我轉生變成史萊姆這檔事 第三季 - 60 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4 >> 關於我轉生變成史萊姆這檔事 第三季 S03E60.mp4
[2024-06-25 21:57:19] INFO:     [FYY GROUP] Mushoku Tensei II - 23 [CRWebRip 2160p HEVC-10bit AAC SCJP].mkv >> Mushoku Tensei II S02E23.mkv
[2024-06-25 21:57:19] INFO:     [Nekomoe kissaten&LoliHouse] Dungeon Meshi - 24 [WebRip 1080p HEVC-10bit AAC EAC3 ASSx2].mkv >> Dungeon Meshi S01E24.mkv
[2024-06-25 21:58:19] INFO:     [Up to 21°C] Hibike! Euphonium 3 - 12 (CR 1920x1080 AVC AAC MKV) [6F74A0E2].mkv >> Hibike! Euphonium 3 S03E12.mkv
[2024-06-25 21:58:19] INFO:     [FYY GROUP] Mushoku Tensei II - 22 [CRWebRip 2160p HEVC-10bit AAC SCJP].mkv >> Mushoku Tensei II S02E22.mkv
[2024-06-25 22:08:57] INFO:     Config loaded
[2024-06-25 22:08:57] INFO:     Config updated
[2024-06-25 22:08:57] INFO:     Config loaded
[2024-06-25 22:08:57] INFO:     Program running.
[2024-06-25 22:09:00] INFO:     Config loaded
[2024-06-25 22:09:00] INFO:     Config updated
[2024-06-25 22:09:00] INFO:     Config loaded
[2024-06-25 22:09:00] INFO:     Program running.
[2024-06-25 22:09:02] INFO:     Start collecting full season...
[2024-06-25 22:09:02] INFO:     Start collecting 无职转生 ～到了异世界就拿出真本事～ Season 2...
Exception in thread Thread-12 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 31, in rss_loop
    eps_complete()
  File "/app/module/manager/collector.py", line 72, in eps_complete
    collector.collect_season(data)
  File "/app/module/manager/collector.py", line 18, in collect_season
    torrents = st.search_season(bangumi)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 54, in search_season
    torrents = self.search_torrents(rss_item)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 24, in search_torrents
    return self.get_torrents(rss_item.url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 22, in get_torrents
    soup = self.get_xml(_url, retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 44, in get_xml
    return xml.etree.ElementTree.fromstring(req.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1345, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
[2024-06-25 22:09:10] INFO:     Config loaded
[2024-06-25 22:09:10] INFO:     Program running.
[2024-06-25 22:09:12] INFO:     Start collecting full season...
[2024-06-25 22:09:12] INFO:     Start collecting 无职转生 ～到了异世界就拿出真本事～ Season 2...
Exception in thread Thread-14 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 31, in rss_loop
    eps_complete()
  File "/app/module/manager/collector.py", line 72, in eps_complete
    collector.collect_season(data)
  File "/app/module/manager/collector.py", line 18, in collect_season
    torrents = st.search_season(bangumi)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 54, in search_season
    torrents = self.search_torrents(rss_item)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 24, in search_torrents
    return self.get_torrents(rss_item.url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 22, in get_torrents
    soup = self.get_xml(_url, retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 44, in get_xml
    return xml.etree.ElementTree.fromstring(req.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1345, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
[2024-06-25 22:39:34] INFO:     Config loaded
[2024-06-25 22:39:34] INFO:     Program running.
[2024-06-25 22:39:36] INFO:     Start collecting full season...
[2024-06-25 22:39:36] INFO:     Start collecting 无职转生 ～到了异世界就拿出真本事～ Season 2...
Exception in thread Thread-16 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 31, in rss_loop
    eps_complete()
  File "/app/module/manager/collector.py", line 72, in eps_complete
    collector.collect_season(data)
  File "/app/module/manager/collector.py", line 18, in collect_season
    torrents = st.search_season(bangumi)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 54, in search_season
    torrents = self.search_torrents(rss_item)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 24, in search_torrents
    return self.get_torrents(rss_item.url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 22, in get_torrents
    soup = self.get_xml(_url, retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 44, in get_xml
    return xml.etree.ElementTree.fromstring(req.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1345, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
[2024-06-25 22:48:13] INFO:     Config loaded
[2024-06-25 22:48:13] INFO:     Program running.
[2024-06-25 22:48:16] INFO:     [RSS] New bangumi founded: 无职转生Ⅱ ～到了异世界就拿出真本事～ 第2部分
[2024-06-25 22:48:19] INFO:     [RSS] New bangumi founded: 吹响！悠风号
[2024-06-25 22:48:21] INFO:     [RSS] New bangumi founded: 关于我转生变成史莱姆这档事
[2024-06-25 22:48:22] INFO:     [RSS] New bangumi founded: 迷宫饭
[2024-06-25 22:48:23] INFO:     Start collecting full season...
[2024-06-25 22:48:23] INFO:     Start collecting 无职转生Ⅱ ～到了异世界就拿出真本事～ 第2部分 Season 2...
Exception in thread Thread-18 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 31, in rss_loop
    eps_complete()
  File "/app/module/manager/collector.py", line 72, in eps_complete
    collector.collect_season(data)
  File "/app/module/manager/collector.py", line 18, in collect_season
    torrents = st.search_season(bangumi)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 54, in search_season
    torrents = self.search_torrents(rss_item)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 24, in search_torrents
    return self.get_torrents(rss_item.url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 22, in get_torrents
    soup = self.get_xml(_url, retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 44, in get_xml
    return xml.etree.ElementTree.fromstring(req.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1345, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
[2024-06-25 22:50:06] INFO:     Config loaded
[2024-06-25 22:50:06] INFO:     Program running.
[2024-06-25 22:50:09] INFO:     Start collecting full season...
[2024-06-25 22:50:09] INFO:     Start collecting 无职转生 ～到了异世界就拿出真本事～ Season 2...
Exception in thread Thread-20 (rss_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/module/core/sub_thread.py", line 31, in rss_loop
    eps_complete()
  File "/app/module/manager/collector.py", line 72, in eps_complete
    collector.collect_season(data)
  File "/app/module/manager/collector.py", line 18, in collect_season
    torrents = st.search_season(bangumi)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 54, in search_season
    torrents = self.search_torrents(rss_item)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/searcher/searcher.py", line 24, in search_torrents
    return self.get_torrents(rss_item.url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 22, in get_torrents
    soup = self.get_xml(_url, retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/module/network/request_contents.py", line 44, in get_xml
    return xml.etree.ElementTree.fromstring(req.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1345, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
```

**Comment by jiaxinonly** [comment]
好像是mikanime.tv的问题，没有返回RSS，我的网络环境下无法正常访问 `https://mikanani.tv/RSS/Search?searchstr=沸羊羊制作+Mushoku+Tensei+II+第二季+简日内封字幕+CRWebRip+2160p` 这个地址，访问会先跳转到`http://ww25.mikanani.tv/`然后再跳转到`http://iyfbodn.com/`，开代理换成 `https://mikanani.me/RSS/Search?searchstr=沸羊羊制作+Mushoku+Tensei+II+第二季+简日内封字幕+CRWebRip+2160p` 就能正常返回RSS

**Comment by jiaxinonly** [comment]
好吧，请原谅我这个新人，修改search_provider.json文件时，域名没改对，只将`.me`改成`.tv`是不对的，正确的是**mikanime.tv**  :sob:
